### PR TITLE
Add config option for "Not in a repo" behavior

### LINKED ISSUE #1091: Setting to disable "Not in a git repository" prompt
**Is your feature request related to a problem? Please describe.**
As a lazygit user, I want to be able to set a default for the `Not in a git repository. Create a new git repository? (y/n):` prompt, so that I don't need to press `n` every time.

**Describe the solution you'd like**
A `notInRepo` setting that can be the following values:
- `prompt` (default) Uses the current prompt
- `create` Creates a repo if one does not exist
- `skip` Does not create a repo

**Describe alternatives you've considered**
A CLI flag (e.g. `--skipRepoPrompt`, or `--alwaysCreateRepo`)

**Additional context**
When you open lazygit in a folder without a git repo, you git the `Not in a git repository. Create a new git repository? (y/n):` prompt as shown in this screenshot: 
image

### PR DESCRIPTION
**Pull request by kalvinpearce**
Fixes #1091 

As stated, super new to go. Please let me know anything you would like fixed up and I would be super happy to 😁

### CODE REVIEW

**Review by jesseduffield — CHANGES_REQUESTED** [review]
Great work! One thing I neglected to say in the original issue is that we should also add the new config key to the config doc: `docs/Config.md`. After that we're good to merge :) 

And good job on your first PR!

**Comment by kalvinpearce** [comment]
Is this okay? And thanks! Hopfully the first of many 🥳

**Review by jesseduffield — APPROVED** [review]
Functionally tested and it works like a charm, great work :)

I'll be using the 'skip' option myself from now on

**Comment by kalvinpearce** [comment]
Thanks! Great to hear. I'd love to move on to another issue or feature, do you have any suggestions that might be good for me or should I just have a look around some more?

**Comment by sportshead** [comment]
@kalvinpearce tysm!! you're a hero!

**Comment by jesseduffield** [comment]
@kalvinpearce great that your keen on contributing more! Anything with the [Good first issue](https://github.com/jesseduffield/lazygit/labels/good%20first%20issue) label is fairly straightforward, but feel free to pick any ticket. Happy to give you pointers. Some tickets are certainly harder than others so don't hesitate to get my thoughts on a solution if it sounds like it's gonna be tricky

**Pull request merged**
