### PR TITLE
Show all submodules recursively

### LINKED ISSUE #3306: Global submodules view
**Describe the solution you'd like**
It would be great if `submodules` tab could show all submodules of the current project recursively. Not only submodules of the current context, but also submodules of submodules, etc. As one list

### PR DESCRIPTION
**Pull request by stefanhaller**
- **PR Description**

Extend the submodules tab to show not only the top-level submodules, but also their nested submodules, recursively.

Fixes #3306.

- **Please check if the PR fulfills these requirements**

* [x] Cheatsheets are up-to-date (run `go generate ./...`)
* [x] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [x] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [ ] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [ ] Docs (specifically `docs/Config.md`) have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

### CODE REVIEW

**Comment by mark2185** [comment]
Tested it, seems to work okay. Perused the code and nothing stood out nor can I think of any problems that might arise. :+1:

**Comment by karimkhaleel** [comment]
Tested it, couldn't find any issues. Looked over the code. LGTM :+1:

**Comment by afhoffman** [comment]
+1, looks good to me too.

**Comment by stefanhaller** [comment]
Three reviews, awesome. Thanks everybody.

There was an integration test failure on git 2.20 though, I added two fixup commits (ad8803bffbcd and 094ccae604b6) to address that. It would be worth looking at those, too. Note that I didn't change the behavior in this branch, we just didn't have tests for that situation before.

**Comment by karimkhaleel** [comment]
Ran the integration tests before and after with different versions of git. Everything checks out. Looked over the fixups too. :+1:

**Pull request merged**
