### PR TITLE
change default to use blue background colour on selected line

### PR DESCRIPTION
**Pull request by jesseduffield**
This PR is not set in stone, I'm willing to think through some different options here.

## The Problem

Due to the diversity of terminal themes out there, just boldening and brightening the text of the selected line is often insufficient to clearly identity the selected line.

Some issues arising from this problem:
https://github.com/jesseduffield/lazygit/issues/1271
https://github.com/jesseduffield/lazygit/issues/1664
https://github.com/jesseduffield/lazygit/issues/1247
https://github.com/jesseduffield/lazygit/issues/1533

We even have a section in the docs to help people who can't see the line, recommending them to use the 'reverse' attribute: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#struggling-to-see-selected-line

### Use the 'reverse' attribute

One of the technical limitations we currently have is that generating the text of a line and highlighting a line happen in two separate places, and so if the 'reverse' attribute is applied, it just goes character by character applying that attribute and that can look really ugly. See https://github.com/jesseduffield/lazygit/issues/1767 for an example. In fact, playing around with the code locally, I'm finding it hard to make the reverse effect not look ugly in general: seems like reverse works best when you're only dealing with a single foreground colour.

I don't think it would look very good to selectively reverse some parts of a line and not others. That said, one thing that reverse has going for it is that it both highlights the line and preserves the contrast so e.g. black text on a white background becomes the equally well-contrasted white text on a black background.

### Use a background colour

Other git TUIs tig and gitui currently take this approach. I find blue to be a sensible background colour and it's usually the darkest in the terminal theme and we also already use it by default in the staging panel when selecting lines to stage.

Using a background colour means you don't get as good contrast as with the reverse attribute, but the result is far less ugly and it requires less maintenance than reverse (e.g. no need to say 'this blank space needs a blue foreground colour so that if it's reversed it doesn't look ugly').

I'm thinking a blue background colour is the way to go. Note this is still just a matter of defaults: the original default as well as the reverse approach are still available.

## What This PR Does

As it stands this PR does the following:
* sets default background to blue
* removes background highlighting on the selected tab because it looked weird (also mentioned in https://github.com/jesseduffield/lazygit/issues/1767)
* sets the background colour on the entire line.
* renders file-trees in a cleaner way

I'm setting the background of the entire line rather than just the selected text because the commits view thanks to its special rendering style was already capturing the entire line and I wanted consistency. Though I could just as easily revert this change and ensure that everything consistently highlights only the line's text. But switching between the two I aesthetically prefer highlighting the whole line.

Lazygit with blue background (new default):
image

Lazygit with reverse attribute:
image
image

Lazygit just using bold text (old default):
image

For comparison, tig highlights the background by default:
image

Gitui highlights the background of just the text portion of the line:
image

### CODE REVIEW

**Comment by peppy** [comment]
I have often had trouble finding the current line (in the diff view most often) so this is a good improvement. I don't find the current default mode on this branch offensive.

iTerm2 2022-04-15 at 01 53 37

The files window does look a bit weird showing (1 of 0) and and empty highlighted line, though.

**Comment by jesseduffield** [comment]
@peppy I agree, that is weird. I'll take a look into that.

In the meantime I'll tag some more people to see if anybody disagrees with this PR's approach @mjarkk @Ryooooooga @mark2185 @matejcik @matt-cles @glendsoza

**Comment by jesseduffield** [comment]
@peppy that issue's fixed now

**Comment by mark2185** [comment]
I've always been unfortunate with default colors in TUIs, the mishmash of blue background and green/red foreground is hard to read (but that might just be due to my choice of terminal emulator and color preferences)

image


That isn't a problem in and of itself since I always change it, but my two cents regarding this

> I don't think it would look very good to selectively reverse some parts of a line and not others.

I think that would actually help readability, only a part of the line would be highlighted and it's easy to draw attention to just that "important" part. I agree with the report in #1767 .

**Comment by jesseduffield** [comment]
Good point @mark2185 . I reckon I'll leave that issue open so we can improve the experience using reverse, but merge this PR as an improvement on the current situation. Supporting partial reversing will take some effort and I'm still not sure it will result in the ideal experience, so I'll let it evolve separately and if we decide that it ends up being superior to the background colour, we can change the default again (I doubt users would mind)

**Comment by jesseduffield** [comment]
On the topic of only reversing certain things (e.g. file/branch name, commit message), I wonder if it would in fact be distracting to be highlighting different bits of a line as you flick through various lines to reach the item that you want. It is nice for the list to remain 'static' while flicking through it. Of course I'm just hypothesising, I haven't actually tried out a partial reverse approach

**Comment by mark2185** [comment]
I think highlighting only a part of the line wouldn't be a problem.

Sure, you're highlighting different bits, but all of them start at the same column, so it's not like your focus would shift left and right, you'd always start reading from the left side of the highlighted area.

**Comment by jesseduffield** [comment]
@mark2185 that is true for all views except the commits view when the graph is shown. In that case things might jump around a bit as you scroll down. Although by default that graph only appears when the commits view is maximised, there's an option to always show the graph which I've got enabled, and I can imagine that feeling a bit jumpy

**Comment by mark2185** [comment]
Fair enough! 

_Someone_ will surely complain if it's too intrusive.

**Comment by jesseduffield** [comment]
Alright I'll merge that bad boy and see how users react

**Pull request merged**
