### PR TITLE
Fix parsing of 'y/n' when starting in non-repo

### LINKED ISSUE #1940: Crash when I try to create a new git repository
**Describe the bug**
I was trying to create a new git repository in a empty folder, I've launched lazygit and at the question create new git repository I've answered yes, this is the error that the terminal has given me:

host> lazygit.exe
Not in a git repository. Create a new git repository? (y/n): y
2022/05/12 01:23:32 An error occurred! Please create an issue at: https://github.com/jesseduffield/lazygit/issues

*errors.errorString Must open lazygit in a git repository
/home/runner/work/lazygit/lazygit/pkg/commands/git.go:187 (0x132e08e)
/home/runner/work/lazygit/lazygit/pkg/commands/git.go:60 (0x132ca45)
/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:480 (0x1393eba)
/home/runner/work/lazygit/lazygit/pkg/app/app.go:138 (0x13feb7d)
/home/runner/work/lazygit/lazygit/main.go:135 (0x140145d)
/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/proc.go:225 (0xd9bfd6)
/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/asm_amd64.s:1371 (0xdcd6a1)

**To Reproduce**
1. Go to an empty folder
2. Launch lazygit
3. Answer yes to question Create a new git repository

**Expected behavior**
It should have been created a new git repository

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Lazygit Version commit=7be25a105d389a262ef040133a4270f2f745d255, build date=2022-03-17T07:07:02Z, build source=binaryRelease, version=0.34, os=windows, arch=amd64

**Additional context**

### PR DESCRIPTION
**Pull request by mark2185**
This should fix #1940, I tested it out and now it actually enters the `if` and inits a new repo.

### CODE REVIEW

**Comment by jesseduffield** [comment]
Interestingly, when I run this locally (on OSX) I get a panic:
```
▶ lg
2022/06/09 20:19:45 An error occurred! Please create an issue at: https://github.com/jesseduffield/lazygit/issues

*errors.errorString Must open lazygit in a git repository
/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:191 (0x1554145)
	navigateToRepoRootDirectory: return errors.New("Must open lazygit in a git repository")
/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:62 (0x1552dc7)
	NewGitCommand: if err := navigateToRepoRootDirectory(os.Stat, os.Chdir); err != nil {
/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:254 (0x1606a65)
	(*Gui).onNewRepo: gui.git, err = commands.NewGitCommand(
/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:562 (0x16091c8)
	(*Gui).Run: if err := gui.onNewRepo(filterPath, false); err != nil {
/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:598 (0x160987c)
	(*Gui).RunAndHandleError.func1: if err := gui.Run(filterPath); err != nil {
/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/utils/utils.go:115 (0x14f5387)
	SafeWithError: err := f()
/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:597 (0x16097ef)
	(*Gui).RunAndHandleError: return utils.SafeWithError(func() error {
/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/app/app.go:207 (0x163927a)
	Run: err := app.Gui.RunAndHandleError(filterPath)
/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/pkg/app/app.go:207 (0x163925e)
	(*App).Run: err := app.Gui.RunAndHandleError(filterPath)
/Users/jesseduffieldduffield/go/src/github.com/jesseduffield/lazygit/main.go:151 (0x1646af6)
	main: app.Run(appConfig, common, filterPath)
/Users/jesseduffieldduffield/.gvm/gos/go1.18/src/runtime/proc.go:250 (0x1036d92)
	main: fn()
/Users/jesseduffieldduffield/.gvm/gos/go1.18/src/runtime/asm_amd64.s:1571 (0x1064ba1)
	goexit: BYTE	$0x90	// NOP
```

Not sure why we're hitting `return errors.New("Must open lazygit in a git repository")`. Does that happen on your end?

**Comment by mark2185** [comment]
Huh, it doesn't happen on my `archlinux` (tried it in a clean docker environment as well).

But it _does_ happen when I press `n` on `macOS`.

I _think_ it's due to the fact that it looks through other repos from the history in `state.yml` and it tries to open the first entry, even though it might be invalid. Could you check if it's due to `state.yml`?

**Comment by jesseduffield** [comment]
I've just tried to reproduce the panic thismorning but wasn't able to: and my state.yml seemed okay. I even planted an invalid path there and didn't get a panic. So I'm not sure what happened there.

At any rate, testing the new code locally works fine :)

**Comment by mark2185** [comment]
I think the edge case was a valid path that doesn't contain a `.git` directory.

**Comment by jesseduffield** [comment]
Ah right

**Pull request merged**
