### PR TITLE
WIP: support alacritty

### PR DESCRIPTION
**Pull request by jesseduffield**
Termbox rejects TERM=alacritty because it doesn't recognise it. I'm adding it in here as a WIP (need to actually fix it in my termbox fork) to see if it works as expected

### CODE REVIEW

**Comment by joshgummersall** [comment]
Here's the output I get building and running locally inside alacritty:

```
jpg@pop-os ~/s/g/s/g/j/lazygit (alacritty)> git log -n 1
commit d4b99259a6ca91c226abe47a87b2dc15e94fc687 (HEAD -> alacritty, origin/alacritty)
Author: Jesse Duffield <jessedduffield@gmail.com>
Date:   Sun Aug 23 20:20:05 2020 +1000

    WIP: support alacritty
jpg@pop-os ~/s/g/s/g/j/lazygit (alacritty)> go build -o lazygit .
jpg@pop-os ~/s/g/s/g/j/lazygit (alacritty)> ./lazygit
2020/08/23 10:00:27 An error occurred! Please create an issue at https://github.com/jesseduffield/lazygit/issues

*errors.errorString termbox: error while reading terminfo data: termbox: unsupported terminal
/home/jpg/src/go/src/github.com/jesseduffield/lazygit/main.go:77 (0xaef7c2)
        main: newErr := errors.Wrap(err, 0)
/home/jpg/.asdf/installs/golang/1.13.8/go/src/runtime/proc.go:203 (0x4310ae)
        main: fn()
/home/jpg/.asdf/installs/golang/1.13.8/go/src/runtime/asm_amd64.s:1357 (0x45cad1)
        goexit: BYTE    $0x90   // NOP
jpg@pop-os ~/s/g/s/g/j/lazygit (alacritty) [1]>
```

I tried to add some debug logging inside the vendor termbox package and didn't see it so maybe I'm missing something though.

**Comment by jesseduffield** [comment]
I think your Go setup isn't using the vendor directory, so it's just pulling my fork directly without the changes. The fact that term=xterm works fine for tells me that we're safe to go with that approach though. I'll go update the fork

**Comment by jesseduffield** [comment]
@joshgummersall I've pushed that change now, are you able to retest?

**Comment by joshgummersall** [comment]
Looks good! Thanks for taking care of this.

**Pull request merged**
