### PR TITLE
Fix function comments with CodeLingo.

### PR DESCRIPTION
**Pull request by BlakeMScurr**
Use [CodeLingo](https://www.codelingo.io/) to automatically fix function comments following the
[effective go guidelines](https://golang.org/doc/effective_go.html#commentary) mentioned in [CONTRIBUTING.md](https://github.com/jesseduffield/lazygit/blob/ba7e6add8690de21239cd0f37ee52a7c50236518/CONTRIBUTING.md).

This patch was generated by running the CodeLingo Rewrite Flow over the ["comment-first-word-as-subject" Tenet](https://github.com/codelingo/codelingo/blob/master/tenets/codelingo/effective-go/comment-first-word-as-subject/codelingo.yaml).

Note: the same Tenet can be used to automate PR reviews and generate guideline docs.

Install CodeLingo: [codelingo.io](https://www.codelingo.io)

### CODE REVIEW

**Comment by glvr182** [comment]
Interesting, I didn't know this tool existed. Is it also able to add comments where non exist?

**Comment by BlakeMScurr** [comment]
@glvr182 It sure can! In fact I just added that capability https://github.com/codelingo/codelingo/pull/266.

Adding a meaningful comment is really an NLP problem, which is not something that CodeLingo focusses on (yet), but we can append placeholder comments these few lines:
```
import codelingo/ast/go

@rewrite --prepend --line "// {{funcName}} is a function."
go.func_decl(depth = any):
  exclude:
    go.comment_group
  go.ident:
    name as funcName
    public == "true"
```

**Comment by BlakeMScurr** [comment]
Obviously `"// {{funcName}} is a function."` is not a massively useful comment, but at least it brings attention to the problem. And you can use CodeLingo to review as well as rewrite - it can comment on your pull requests when you write a function that's missing a comment, then a human can manually write it.

**Comment by BlakeMScurr** [comment]
Actually I just found out that we’re working on an interactive review command which would come in really handy here. You’ll be able to install our CLI tool and run `lingo run rewrite` which will prompt you to write your own comment where none exists. Would you guys like to be our alpha testers for it?

**Comment by BlakeMScurr** [comment]
[Discuss post on interactive rewriting](https://discuss.codelingo.io/t/interactive-rewrite/84)

**Comment by jesseduffield** [comment]
Sounds cool to me, I'm happy to alpha test

**Comment by jesseduffield** [comment]
thanks for making this PR btw, very cool :)

**Comment by BlakeMScurr** [comment]
No problem I'm glad you like it! You can get it running automated code reviews on all your PRs by installing our GitHub app https://github.com/apps/codelingo.

The fun part is definitely writing your own custom tenets (linter/rewrite rules) though - so feel free to hop in [our slack](https://join.slack.com/t/codelingo/shared_invite/enQtNDYxOTYyNTI5NjUwLWFiNjFjOTM3YzgzMjA4NjNiNDhmN2RkZWNlODM0ZTM5NTkzOThhZjczN2ZlYmNkMjhkNDBkYjBlMjQ1NDk2NTQ) :)

**Comment by BlakeMScurr** [comment]
By the way, it'd be great to get a tweet if you're up for it. Something like "@codelingoapp just fixed my bugs!" Thank you!

**Pull request merged**
