### PR TITLE
Change the way file statuses are loaded

### PR DESCRIPTION
**Pull request by mjarkk**
Should fix the second comment in #1385

### CODE REVIEW

**Comment by mjarkk** [comment]
Closing as this does not fix the core problem

**Comment by mjarkk** [comment]
A few lines above this fix there is this line: `statusStrings := utils.SplitLines(statusOutput)`

I think that's where the problems came from in the first place.  
If we add another one like that that also checks for quoted git file names like ("a\nb") i think we can solve it that way.  
Once we have that we can check in the for loop if there are \n / \r chars and if so log an error message that the file is unusable.

**Comment by ebudan** [comment]
Looks like Go's exec.Cmd already strips those quotes. Logical enough - something coming from the shell, in quotes, is interpreted as a string, quotes now superfluous. 

This is the closest I'm getting to a fix while avoiding any major restructuring:

```
diff --git a/pkg/commands/loading_files.go b/pkg/commands/loading_files.go
index 3e36809f..43fa5979 100644
--- a/pkg/commands/loading_files.go
+++ b/pkg/commands/loading_files.go
@@ -96,6 +96,9 @@ func (c *GitCommand) GitStatus(opts GitStatusOptions) (string, error) {
        // if a line starts with 'R' then the next line is the original file.
        for i := 0; i < len(splitLines)-1; i++ {
                original := splitLines[i]
+               if !sanityCheck(original) {
+                       c.Log.Warnf("invalid file name: '%s'", original)
+               }
                if strings.HasPrefix(original, "R  ") {
                        next := splitLines[i+1]
                        updated := "R  " + next + RENAME_SEPARATOR + strings.TrimPrefix(original, "R  ")
@@ -106,3 +109,13 @@ func (c *GitCommand) GitStatus(opts GitStatusOptions) (string, error) {
 
        return strings.Join(splitLines, "\n"), nil
 }
+
+func sanityCheck(fname string) bool {
+       if strings.TrimSpace(fname) != fname {
+               return false
+       }
+       if strings.Index(fname, "\n") != -1 {
+               return false
+       }
+       return true
+}
```

Code style aside, the sanity check should probably be more complete, and logging to the dev debug file might not be the clearest feedback to the casual user.

**Comment by mjarkk** [comment]
Just did some looking into the code and found we are using the -z argument:
```
$ git status --porcelain
 M pkg/commands/loading_files.go
?? "a\nb"

$ git status -z
 M pkg/commands/loading_files.go?? a
b
```

git-status manual say this:
```
       -z
           Terminate entries with NUL, instead of LF. This implies the --porcelain=v1 output
           format if no other format is given.
```

After the command is executed we transform it back to a normal string with \n's in between so maybe we should'd do that and just return an array of strings
`pkg/commands/loading_files.go:97`

**Comment by mjarkk** [comment]
@ebudan can you re-checkout this branch's code?  
It should now be more solid hopefully.  
Still need to implement the warning tough.

**Comment by mjarkk** [comment]
@ebudan Would you like to verify if these changes no longer cause errors when opening lazygit with wired filenames?

**Comment by ebudan** [comment]
Late commenting, but makes sense to simplify that return value, and works with my stupid-file-names-with-newlines.  
(This does make me wonder if there are many more places where a newline-separated string is rebuilt, but that would be a different code vetting issue.)

**Comment by mjarkk** [comment]
Was thinking about that too and the commit files panel was also broken so fixed that too in this PR.
Files tree view and stash also seem to work fine now.

**Pull request merged**
