### PR TITLE
add URL encoding in pull request link creation

### PR DESCRIPTION
**Pull request by MikaelElkiaer**
Closes https://github.com/jesseduffield/lazygit/issues/1485

### CODE REVIEW

**Comment by jesseduffield** [comment]
@MikaelElkiaer thanks for making this. Given that I don't expect us to come across a git hosting site that doesn't need from/to to be escaped: could we instead centralise the escaping to the `PullRequestURL` method in the same file?

**Comment by MikaelElkiaer** [comment]
> @MikaelElkiaer thanks for making this. Given that I don't expect us to come across a git hosting site that doesn't need from/to to be escaped: could we instead centralise the escaping to the `PullRequestURL` method in the same file?

That makes sense, I'll change that once I get the chance.

**Review by jesseduffield — CHANGES_REQUESTED** [review]
marking as changes requested for my own bookkeeping :)

**Comment by jesseduffield** [comment]
@MikaelElkiaer nice one. Could you add a test to `pkg/commands/hosting_service/hosting_service_test.go`?

**Comment by MikaelElkiaer** [comment]
@jesseduffield Updated. It seems like pretty much all of the existing tests were affected, as most of them used `/` in the branch names, which is now escaped as `%2F`. I added two specific tests as well.

**Review by jesseduffield — CHANGES_REQUESTED** [review]
@MikaelElkiaer looks good to me. Looks like you just need to fix up a couple of linting issues

**Comment by MikaelElkiaer** [comment]
> @MikaelElkiaer looks good to me. Looks like you just need to fix up a couple of linting issues

@jesseduffield There we go. Stupid nvim added spaces instead of tabs - so much for "smartindent".

**Comment by jesseduffield** [comment]
Looks like we need just one more round of lint-fixing haha

**Comment by MikaelElkiaer** [comment]
> Looks like we need just one more round of lint-fixing haha

That's pretty annoying. What can I set up locally to follow your ruleset?

**Comment by jesseduffield** [comment]
If I run `go fmt pkg/commands/hosting_service/hosting_service_test.go` that fixes the issue for me. I use vscode and I believe it runs go fmt upon save (I'm using the standard Go extension)

**Comment by MikaelElkiaer** [comment]
Fingers crossed. Thanks for the pro tip regarding `go fmt`. I do remember VSCode being annoying and changing your code with the Go extension.

**Comment by jesseduffield** [comment]
Merged! Thanks for making this

**Comment by bezlant** [comment]
hey, @MikaelElkiaer  in my case i get in target branch / encoded as release%252Fbranch in the gitlab url and it is not able to find my branch, since gitlab decodes it as release%2Fbranch, any ideas how could I fix it?
thanks <3

**Comment by MikaelElkiaer** [comment]
@bezlant That sounds like it's being encoded twice.
If this has worked previously, it must be a regression that came after this PR.

**Pull request merged**
