### PR TITLE
added branch delete functionallity

### PR DESCRIPTION
**Pull request by hubertba**

### CODE REVIEW

**Comment by jesseduffield** [comment]
Absolutely nailed it man thanks for doing this

**Comment by hubertba** [comment]
was a pleasure for me ... after 20 years of programming .. did my first pull request to an open source project :-) ( in a language I didn't know :-))

**Comment by jesseduffield** [comment]
haha that's awesome, this project is my first taste of open source as well and my first project using Go! 

If you have any other ideas for features please let me know / put up another PR :)

**Comment by hubertba** [comment]
I try to use it and if I find some things I would like to have, I will implement it and send you a PR :-)

**Pull request merged**
