### PR TITLE
fix(icons): replace deprecated nerd-fonts icons

### PR DESCRIPTION
**Pull request by carlosala**
- **PR Description**
Replace deprecated nerd-fonts icons from v3 on.

- **Please check if the PR fulfills these requirements**

* [ ] Cheatsheets are up-to-date (run `go run scripts/cheatsheet/main.go generate`)
* [x] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [ ] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [ ] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [ ] Docs (specifically `docs/Config.md`) have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

### CODE REVIEW

**Comment by David-Else** [comment]
Brilliant! This fixes the super annoying font problems I have had with [v2.3.3](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.3) `Symbols-2048-em Nerd Font Complete Mono.ttf` in Kitty. 

I tried copying and pasting the new and old from this pull request in the terminal, and it looks much better:

Screenshot from 2023-05-04 11-58-35

**Comment by jtrv** [comment]
@David-Else In my PR I changed the nerdfont character in the comment next to the code point in the same way this PR does, but the code points here are invalid. When I tried using the correct code points on my branch they didn't seem to be read correctly, so I've closed my pr until I can figure out how to get it working properly.

**Comment by gotgenes** [comment]
I made an alternative PR that uses higher order unicode code points. #2604

**Comment by carlosala** [comment]
Closed in favour of #2604

**Pull request closed without merging**
