### PR TITLE
feat(i18n): add russian translation

### PR DESCRIPTION
**Pull request by letavocado**
**PR Description**

This translation is for Russian users.

---

- **Please check if the PR fulfills these requirements**

* [x] Cheatsheets are up-to-date (run `go run scripts/cheatsheet/main.go generate`)
* [x] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [ ] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [x] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [x] Docs (specifically `docs/Config.md`) have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

### CODE REVIEW

**Comment by jesseduffield** [comment]
I don't speak Russian so I can't judge the quality of these translations but I trust that you've done your due diligence. Looks like you need to run `go run scripts/cheatsheet/main.go generate` again though

**Comment by letavocado** [comment]
Hi @jesseduffield! Thanks! I've used [gitbook](https://git-scm.com/book/ru/v2) for more accurate translation. I :heart: lazygit!

Cheers!

**Comment by letavocado** [comment]
@jesseduffield

> `go run scripts/cheatsheet/main.go generate`

I've ran it and force-pushed. Please check, and feel free to tell me what to change or run.

Cheers!

**Comment by letavocado** [comment]
Hey @jesseduffield.
Sorry, my bad. I've fixed lint errors, double checked and ran lint `golangci-lint` to be sure.

Cheers!

**Comment by letavocado** [comment]
Hey @jesseduffield! 

- [x] rebased
- [x] Updated with latest changes
- [x] `go run scripts/cheatsheet/main.go generate`
- [x] `golangci-lint` 

Cheers!

**Comment by jesseduffield** [comment]
Great work @letavocado , thanks for making this

**Pull request merged**
