### PR TITLE
Add new filter to only show tracked files in Files panel

### PR DESCRIPTION
**Pull request by veremenko-y**
- **PR Description**

Added new filter to only show tracked files in Files panel. This allows to hide all non-tracked files on large repos.

- **Please check if the PR fulfills these requirements**

* [x] Cheatsheets are up-to-date (run `go generate ./...`)
* [x] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [x] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [x] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [ ] If a new UserConfig entry was added, make sure it can be hot-reloaded (see [here](https://github.com/jesseduffield/lazygit/blob/master/docs/dev/Codebase_Guide.md#using-userconfig))
* [ ] Docs have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

FYI This is my first PR in this repo.

### CODE REVIEW

**Review by jesseduffield — APPROVED** [review]
LGTM

**Comment by veremenko-y** [comment]
Anything else is needed from me for this PR?

**Comment by jesseduffield** [comment]
Nope I just gotta rebase+merge this guy

**Comment by salmiakki** [comment]
@veremenko-y Is it possible to default to `Show only tracked`?

**Pull request merged**
