### PR TITLE
Add field Alternative to gui.Binding

### LINKED ISSUE #423: scroll keybindings for mac
**Is your feature request related to a problem? Please describe.**
Right now, the scroll keybindings shown in the default screen on running `lazygit` as well as the [/docs/keybindings/Keybindings_en.md](https://github.com/jesseduffield/lazygit/blob/master/docs/keybindings/Keybindings_en.md) file show this:

<pre>
  <kbd>PgDn</kbd>: scroll down
  <kbd>PgUp</kbd>: scroll up
</pre>

However these keys do not exist on mac(right?). I came across the correct keybindings in #25. 

**Describe the solution you'd like**
Ideally, the keybindings shown at the bottom on running `lazygit` would be OS aware. Furthermore, the `Keybindings.md` file should call out the different keybinding on mac. I'd be happy to work on these if you could give me some pointers on where the changes would need to be done.

### PR DESCRIPTION
**Pull request by sudo-suhas**
Document and use alternative keybinding for generating cheatsheet. Add
alt keybinding `fn+up/down` for scroll up/down actions.

Closes #423.

### CODE REVIEW

**Comment by jesseduffield** [comment]
Looks good! Please run `go run scripts/generate_cheatsheet.go` and add the resulting files to this PR :)

**Comment by sudo-suhas** [comment]
> Looks good! Please run `go run scripts/generate_cheatsheet.go` and add the resulting files to this PR :)

Done. Also rebased on origin/master.

**Comment by jesseduffield** [comment]
It appears that `fn` doesn't show up anywhere on the cheat sheets. Perhaps the scroll keybindings aren't being shown there for some reason

**Comment by sudo-suhas** [comment]
My apologies for not noticing that. I have made the changes which add the alternative keybinding to docs. Like you said this isn't DRY but it's better than nothing.

W.R.T `generate_cheatsheet.go`, the files it generates are not deterministic and the order of section can change because `map`s make no guarantees about order of iteration. Is minimal manual intervention acceptable?

**Comment by jesseduffield** [comment]
Looks good to me! thanks for making this :)

**Pull request merged**
