### PR TITLE
Add squash merge support

### PR DESCRIPTION
**Pull request by rodakd**
- **PR Description**

I do `git merge --squash branch` a lot so I've added this shortcut for myself. I think some people may want this too so here it is.

- **Please check if the PR fulfills these requirements**

* [x] Cheatsheets are up-to-date (run `go generate ./...`)
* [x] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [x] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [x] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [x] Docs (specifically `docs/Config.md`) have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

### CODE REVIEW

**Review by stefanhaller — COMMENTED** [review]
Nice, thanks for the contribution. I also use this command a lot, and have configured a custom command for it.

One general thought: in my custom command I went one step further and also make a commit; I found that I want this pretty much 100% of the time, and having to do it manually is annoying. And frankly I wouldn't know what else you would do with the squashed changes in your working copy, other than committing them. Do you think this is a general enough workflow that it makes sense to have your new command do that too? For reference, my custom command is
```
- key: "S"
    command: 'git merge --squash --ff {{.SelectedLocalBranch.Name}} && git commit -m "[SQUASHED] {{.SelectedLocalBranch.Name}}"'
    context: "localBranches"
    description: "Merge squashed branch"
```

**Comment by stefanhaller** [comment]
@rodakd I haven't heard from you again after giving feedback; do you intend to keep working on this?

**Comment by noahfraiture** [comment]
Hello since there's no news, should I remake a PR with theses changes ?

**Comment by stefanhaller** [comment]
> Hello since there's no news, should I remake a PR with theses changes ?

I wouldn't have any objections to that. I would, however, be interested in discussing [this question](https://github.com/jesseduffield/lazygit/pull/3130#pullrequestreview-1748802657) first. Any thoughts on that?

**Comment by noahfraiture** [comment]
> > Hello since there's no news, should I remake a PR with theses changes ?
> 
> I wouldn't have any objections to that. I would, however, be interested in discussing [this question](https://github.com/jesseduffield/lazygit/pull/3130#pullrequestreview-1748802657) first. Any thoughts on that?

I personally have no objection but in my use case I don't always make a commit, I might divide the changes in multiple commits or remove some change. However, having a formatted message showing well that it is a merge could be good for clarity and commit are always editable. Maybe having both good be great, but it requires to either open a new window like for rebase options, or having to keys which might a bit too much. What do you think ?

**Comment by stefanhaller** [comment]
We probably want to have a confirmation panel anyway (this PR has one). Instead of the confirmation panel we could show a menu with two options, something like this, maybe:

```
+-- Squash Merge "my-feature" into current branch --+
|c Squash Merge and commit                           |
|u Squash Merge and leave uncommitted                |
|  Cancel                                            |
+---------------------------------------------------+
```
Or something along these lines. I would vote for making the "and commit" version the first one, as I think it's the more common one.

**Comment by jesseduffield** [comment]
This was completed in https://github.com/jesseduffield/lazygit/pull/3566. Thanks for getting the ball rolling on it!

**Pull request closed without merging**
