### PR TITLE
Add SSH key passphrase prompt to pull/push from/to remote git repo

### PR DESCRIPTION
**Pull request by band-a-prend**
This commit resolves issue with absence of ssh key prompting
to pull from or push to remote git repository.

I checked lazygit with this patch for successfully pull from
and push to https://gitweb.gentoo.org/repo/proj/guru.git repository.
While for lazygit-0.23.1 I'm not able to do that.

The check for Passphrase follows the Password because of
more long time before SSH key is prompt in terminal.
Otherwise after timeout "Password" prompt is appears.

Excuse me for google translated i18n dutch lines.

Bug: https://github.com/jesseduffield/lazygit/issues/534

Signed-off-by: band-a-prend <torokhov-s-a@yandex.ru>

### CODE REVIEW

**Comment by band-a-prend** [comment]
Excuse me, I'm confused about `Format code` error of CI check.

**Comment by jesseduffield** [comment]
@band-a-prend the format error wants you to align the values in the prompts map

**Review by jesseduffield — CHANGES_REQUESTED** [review]
Code LGTM, just fix up that formatting issue and we can merge :)

**Comment by band-a-prend** [comment]
> @band-a-prend the format error wants you to align the values in the prompts map

I fix it with `gofmt -w os.go`

**Comment by jesseduffield** [comment]
Thanks for making this :)

**Pull request merged**
