### PR TITLE
auto-stage all when committing if no staged files and configured to do so

### PR DESCRIPTION
**Pull request by fluffynuts**
This is an attempt to address https://github.com/jesseduffield/lazygit/issues/1079

*massive disclaimers*: 
- I'm not a go master
- I don't know how to implement unit tests for this (and there really should be some, surely?)
- I don't even know how to 'go get' this after I did so on the original repo. I've been working under Linux for this, so once I `go [got]` your version, I appear to be stuck with that; even after rm -rf on the go workspace, things turn out bad (see logs below), so I'm not sure of the correct way to test this
- I ended up doing a `go build` in my fork's local folder, modifying a file after configuring with my desired flag & then hitting `c` -- no prompt, so win, I guess? Feels a little hollow without a test :/

"logs below"

from attempting to `got get` my fork:
```
go: downloading github.com/fluffynuts/lazygit v0.23.7
go: github.com/fluffynuts/lazygit upgrade => v0.23.7
go get: github.com/fluffynuts/lazygit@v0.23.7: parsing go.mod:
        module declares its path as: github.com/jesseduffield/lazygit
                but was required as: github.com/fluffynuts/lazygit
```

which makes sense since the package name including `jesseduffield` is scattered throughout the module, so the question I have is this: how do people do forks & testable PRs for go modules? or is this just known in the go community? Again, I'm no go-pro (ha! see what I did there!), so I'm probably missing something obvious.

### CODE REVIEW

**Comment by fluffynuts** [comment]
please excuse sassy PR -- I'm no go guru, but there are aspects of the tooling/language which I really like and I'd like to understand more.

At any rate, I think this solves the issue; would appreciate guidance on an automated test tho'.

**Comment by fluffynuts** [comment]
@jesseduffield not sure if I've done something super wrong on this PR, would appreciate feedback.

**Comment by fluffynuts** [comment]
erk, thought I was doing a good thing rebasing on upstream master, but now I fail lint checks )':

**Comment by jesseduffield** [comment]
@fluffynuts we recently merged a thing that introduces linting to PRs. I'll need to go and fix those lint errors; don't worry about them for now! I'll also try and review this PR soon

**Comment by jesseduffield** [comment]
@fluffynuts I've merged a PR that fixes all these linting issue so if you rebase onto master the errors should go away :)

**Comment by fluffynuts** [comment]
eh, I think that github doesn't like my force-push after the rebase & squishing all commits into one with a decent message; I'll re-open this.

**Pull request closed without merging**
