### PR TITLE
Fix format issue

### PR DESCRIPTION
**Pull request by antham**
This PR fix tests broken on master

### CODE REVIEW

**Comment by antham** [comment]
@jesseduffield there was a formatting issue, I think it came from the master branch to avoid such thing I think it could be great to force in master branch setting to be up to date with master, this way you need to pick last changes.

**Comment by jesseduffield** [comment]
LGTM :)

how would you go about forcing something like that?

**Comment by antham** [comment]
In settings > branches 

capture d ecran 2018-08-27 a 10 05 54

**Comment by antham** [comment]
Did you see my last comment @jesseduffield ?

**Comment by jesseduffield** [comment]
I didn't see it until just now. I've put this rule in for the master branch. Is that sufficient?

image

**Comment by antham** [comment]
@jesseduffield yes it's working I see a sync request in my pending PR

**Pull request merged**
