### PR TITLE
move toplevel keybindings out of global view space

### LINKED ISSUE #1628: Pop-up windows don't disable irrelevant key mappings
**Describe the bug**
Pop-up windows don't disable shortcuts, e.g. the prompt `Are you sure you want to quit?` allows me to press `z` and trigger `undo`. Or even press `x` to bring up the menu.

**To Reproduce**
1. Set `confirmOnQuit: true` in your config
2. Press `q` in `lazygit`
3. Press `x` or `z`
4. It does the action that the key is mapped to

**Expected behavior**
Pressing things not relevant to the pop-up shouldn't do anything

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: archlinux
 - Lazygit Version 0.31.4
 - The last commit id if you built project from sources: N/A

**Additional context**
The reason I press `z` instead of `y` when quitting is because I often switch between two keyboard layouts and forget what's the current one I'm using.

### PR DESCRIPTION
**Pull request by escrafford**
fixes #1628 and part of #1507 ... There were a couple ways to go about solving the key binding vs top view problem, this seemed the most "correct" based on keybindings being attached to views. let me know if you would rather this be solved a different way. also... there was a lot of moving bindings around and reformatting them - hopefully I didn't accidentally break one.

### CODE REVIEW

**Comment by escrafford** [comment]
a) cool tests! b) looks like I broke some with this patch. looking at other ways to go about this, and learning lots about the codebase in the process :)

**Comment by escrafford** [comment]
with the extra toplevel views in my last commit, I can get the tests to pass on a week old tree or so, but not today's tree (it breaks on pushTag). Not sure why? Also not sure if menu should be in the list of views that all the keybindings are applied to or not. I added it back in during the last commit, but maybe it shouldn't be

**Comment by escrafford** [comment]
pulled menu back out of the toplevel list, and added keybindings specific to menus to close them. unfortunate that this works on every popup menu, but that seems like the lesser evil. seems like keybinding stuff would be simpler if it were part of View instead of its own thing? I'll need to read through more code tomorrow.

**Review by jesseduffield — CHANGES_REQUESTED** [review]
Sorry for taking so long to get around to reviewing this! Thanks for making this PR, I'm fully on board with the change.

One thing we'll want to do is continue having our cheatsheet showing these commands as 'global'. We already have the ability for bindings to be 'tagged' e.g. for our 'navigation' bindings, and I think we should tag these as global. That way in `pkg/cheatsheet/generate.go` we can put global keybindings in their own category in `getHeaders` like so:
```go
	if binding.Tag == "global" {
		return []header{{priority: 2, title: localisedTitle(tr, "global")}}
	}
```
Currently in that function we identify global bindings by having an empty view name but now that criterion is invalid.

Another tricky thing we'll have to do is deal with the recent refactor which defined some global controllers, meaning some global keybindings are now defined through those rather than in this keybindings file. My long-term direction was to get everything in this file into a controller but the refactor was taking so long that I decided to merge it and continue the work gradually. So we'll need to handle the global controllers within the loop that goes `for _, c := range self.State.Contexts.Flatten() {`, by checking if the context key is `GLOBAL_CONTEXT_KEY` and if so, adding one binding per view name in that list of side views.

Let me know if that makes sense and if you need any clarification. Again, apologies for the late review, but this PR will have a great impact!

**Comment by jesseduffield** [comment]
@escrafford I'm closing this due to staleness, but let me know if you want to continue on this and we can re-open

**Pull request closed without merging**
