### PR TITLE
feat: create environment for every PR using Uffizzi

### PR DESCRIPTION
**Pull request by daramayis**
**PR Description**

This PR is a part of https://github.com/jesseduffield/lazygit/issues/2234 and helps demonstrate Uffizzi integration with lazygit. This will help create preview environments on all of lazygit Pull Requests and help contributors including the maintainers iterate faster on their PRs. 
I have created a PR over https://github.com/daramayis/f-lazygit/pull/1#issuecomment-1306672596 to show what it looks like to have a preview environment deployed against your PR.

You can check out the preview over [here](https://app.uffizzi.com//github.com/daramayis/f-lazygit/pull/1) as well.

@waveywaves

### CODE REVIEW

**Comment by jesseduffield** [comment]
Thanks @daramayis I'm interested in seeing how useful this could be for us. One thing is that opening lazygit on its own isn't particularly useful: typically a PR is trying to address some problem, and the expectation is that the PR adds one or more integration tests to verify the change. So I'd like to see `go run cmd/integration_test/main.go tui` be invoked instead of lazygit, which brings up a terminal UI that allows you to select integration tests to run (either directly or in a sandbox mode where you can click around yourself).

Currently that program will compile lazygit before running it for a given integration test. If that proves too slow for our test box we could instead pre-compile lazygit and pass an env var or argument to the `tui` program to use the pre-compiled lazygit, so that the docker file can compile lazygit once without us having to do it within the running container.

On a separate note, how would one typically go to the link? Would a bot post a comment on the PR with a link to the new session every time a commit is pushed?

**Comment by jesseduffield** [comment]
Also tagging @mark2185 and @Ryooooooga for their thoughts. Do you think this would prove useful?

Thinking out loud: one potential use case is for people who want to demonstrate some bug: they could create a PR containing an integration test which demonstrates the problem, and then a contributor could verify it without needing to check out the branch. Having said that, if somebody is willing to go and create an integration test for the sake of reproduction, they'd probably be willing to just fix the issue itself.

**Comment by mark2185** [comment]
> Having said that, if somebody is willing to go and create an integration test for the sake of reproduction, they'd probably be willing to just fix the issue itself.

Exactly.

I'd rather not the burden on the reporter.

What it might come handy for is maybe presenting new features, e.g. "look at these new icons", or "could you try to reproduce your bug on this branch, to see if it's fixed" for people not willing or able to build a custom branch. But that often requires a custom setup, a private repo, or something else.

I dunno, I'm not quite sold on it (at least not yet), but maybe I'm not the target audience.

**Comment by daramayis** [comment]
Hi @jesseduffield and @mark2185 ,
I have fixed and now we run the tests — `go run cmd/integration_test/main.go tui`.
Here you can check https://app.uffizzi.com//github.com/daramayis/f-lazygit/pull/1

**Comment by jesseduffield** [comment]
@daramayis testing that out I see visual artefacts: 
image

I assume you need to bump your xterm library or something.

It's also still quite slow. Is it possible to speed it up?

**Comment by jesseduffield** [comment]
Sweet, so is this PR good to merge?

**Comment by jesseduffield** [comment]
@daramayis it's now merged :) sorry for the wait

**Pull request merged**
