### PR TITLE
Improve Dutch in Keybindings_nl.md

### PR DESCRIPTION
**Pull request by teunissenstefan**

### CODE REVIEW

**Comment by jesseduffield** [comment]
Thanks for making this :) the dutch keybindings are actually auto-generated via `go run scripts/generate_cheatsheet.go`, which pulls the language from `pkg/i18n/dutch.go`. Would you be able to make these changes in that file?

**Comment by teunissenstefan** [comment]
I'll do my best

**Comment by teunissenstefan** [comment]
@jesseduffield Better? I only added strings to dutch.go for the .md file to be up to date

**Review by mjarkk — APPROVED** [review]
LGTM

**Comment by jesseduffield** [comment]
@teunissenstefan looks like there are some conflicts due to a recently merged PR. I would rebase onto master and then re-generate these keybindings files to get around the conflicts :) (if you need guidance lemme know)

**Comment by jesseduffield** [comment]
Just fixed those conflicts myself, though I expected this PR to then be merged automatically as a result when I pushed to master. In any case I'll close this PR now, but your commits are in!

**Pull request closed without merging**
