### PR TITLE
#158: escapes backticks, which is a problem in shells like Bash

### PR DESCRIPTION
**Pull request by remyabel**

### CODE REVIEW

**Comment by jesseduffield** [comment]
nice man this is perfect. Just one thing before I merge, can you run gofmt on this? the spacing in testQuote should be like so:
```
	osCommand := &OSCommand{
		Log:      nil,
		Platform: getPlatform(),
	}
```

**Comment by jesseduffield** [comment]
@sanbornm does this PR work for you? If so I'm happy to merge

**Comment by jesseduffield** [comment]
mergin'

**Comment by sanbornm** [comment]
@jesseduffield I can confirm that this _does_ fix my original complaint. Thanks! :+1:

**Pull request merged**
