### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by jfcg**
Add Github CodeQL security checks for Go.

### CODE REVIEW

**Comment by jesseduffield** [comment]
@jfcg could you provide some context for this PR please?

**Comment by jfcg** [comment]
codeql has some nice checks, see https://securitylab.github.com/tools/codeql

**Comment by jesseduffield** [comment]
Interesting. Looks like it hasn't found any issues. That surprises me: typically whenever adding some new tool like this on CI it finds hundreds of issues. That makes me think one of the following is true:
1) this codebase is very secure
2) this CI step isn't actually working
3) this tool is not intended for offline applications like lazygit and therefore provides no value.

What are your thoughts?

**Comment by jfcg** [comment]
it has many checks for web apps, you are right. it could be less useful for this case.

**Comment by eruizc-dev** [comment]
It is true that there have been lots of PR trying to introduce backdoors in some projects, but as mentioned by Jesse: does it really add any value here?

**Pull request closed without merging**
