### PR TITLE
Use Nerd Font Icons for pull and push

### PR DESCRIPTION
**Pull request by joshmedeski**
Adds Nerd Font icons for git push and pull.

- **Please check if the PR fulfills these requirements**

* [x] Cheatsheets are up-to-date (run `go run scripts/cheatsheet/main.go generate`)
* [x] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [x] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [x] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [x] Docs (specifically `docs/Config.md`) have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

### CODE REVIEW

**Comment by joshmedeski** [comment]
@jesseduffield can you review this?

**Comment by stefanhaller** [comment]
Could you post a screenshot of how this looks for you? I just tried it, and it looks terrible on my screen. I'm using SauceCodePro Nerd Font 13, and I can hardly recognize the icons; also, the spacing is weird.
image

I much prefer the arrows from master.

**Comment by joshmedeski** [comment]
I chose the `nf-cod-repo` push and pull icons. Perhaps people won't want to use these icons so I'm open to another solution but I prefer it.

I added a space between push and pull when both are present to help fix the Nerd Font rendering issue, here is how it looks in Kitty with a fallback font (instead of a patched font).

Screenshot 2023-06-23 at 10 08 01 AM

**Comment by mark2185** [comment]
Just my two cents - I much prefer the two arrows we have had so far
image

**Comment by joshmedeski** [comment]
Sounds the strategy for adding new Nerd Font icons with the`showIcons` config option isn't going to work here.

I could add new values to the config that let users individually overwrite icons to their liking.

**Comment by stefanhaller** [comment]
I find these icons much harder to decipher, and I also find them unintuitive with one having the arrow point up and the other sideways. The existing arrows are both very intuitive, and much clearer visually.

I also think that such a change doesn't warrant a new config setting, so I have to say that I'm opposed to this change, sorry.

**Comment by joshmedeski** [comment]
So I made lots of icon changes on https://github.com/jesseduffield/lazygit/pull/1934 and it ultimately didn't get merged.

I want to go through one-by-one and add Nerd Font icon support that I prefer in my git workflow. So ultimately changing direction to a allowing individuals to decide which icons they want to overwrite seems like a good idea as I offer more support throughout the UI since most people don't find my proposed changes helpful to their workflow.

If I have to maintain a fork of lazygit so-be-it, but I'd rather allow better customizability for those that do want it.

**Comment by jesseduffield** [comment]
Sorry for the late review @joshmedeski . I agree with @stefanhaller, I don't find these icons intuitive and I don't want to increase the complexity of the codebase by adding another config option for them. If enough people say that they want more icons I'll be happy to reconsider, but at the moment I don't see the value in it.

**Comment by joshmedeski** [comment]
Alright, thanks for being transparent. I'll close this PR and manage a fork of my own in the meantime.

**Pull request closed without merging**
