### PR TITLE
Toast notifications

### PR DESCRIPTION
**Pull request by jesseduffield**
This allows toast notifications to be created for when you want to show the user a message that's not very intrusive. This PR adds toast notifications for when the user copies an item to the clipboard.

the term 'toast' usually applies because the thing should pop up like toast in a toaster but in this case there's no real animation. We could have it slide in from the side but I feel like that would be overkill (although it would also look very cool).

### CODE REVIEW

**Comment by jesseduffield** [comment]
Forgot to tag you earlier @farzadmf but this PR might be of interest

**Comment by farzadmf** [comment]
Interesting @jesseduffield :slightly_smiling_face: I'll look into changing mine.

Also, a general question: I'm using the AUR package of `lazygit`. How long does it for a new version to be available when a PR is merged to master?

**Comment by jesseduffield** [comment]
Very good question, which I actually don't know the answer to  :). Taking a look at the AUR repo page I can't see any indication Perhaps you might know @dawidd6 ?

**Comment by dawidd6** [comment]
I don't use Arch and don't know anything about the package in AUR. @frealgagu seem to be the maintainer.

**Comment by frealgagu** [comment]
I try to update it ASAP, however if you flag the AUR package I'll be aware and update it sooner.

**Comment by farzadmf** [comment]
So maybe my question for you @jesseduffield is: how often is a release created in GitHub? :slightly_smiling_face:

**Comment by jesseduffield** [comment]
Good question @farzadmf , typically I'll merge a few PRs and continue using lazygit during the week before releasing so that I'm more confident there are no bugs, but it's not very rigid. I'll see if I can do a release today

**Comment by farzadmf** [comment]
Makes perfect sense @jesseduffield

**Pull request merged**
