### PR TITLE
suggest files when picking a path to filter on

### PR DESCRIPTION
**Pull request by jesseduffield**
fixes https://github.com/jesseduffield/lazygit/issues/1525

### CODE REVIEW

**Comment by screendriver** [comment]
> does it say that it's loading anything in the bottom left?

unfortunately not

Screenshot 2021-10-18 at 11 15 02

**Comment by jesseduffield** [comment]
@screendriver I've fixed the issue with ignoring every file if `.*` appears in the gitignore. As for not finding all files: yes we cut off the list at 20 items. Do you have an example of a file in lazygit that I can check against?

**Comment by jesseduffield** [comment]
@screendriver the reason is that those results actually do contain the word 'loading' but spread over quite a few characters. We see the same thing in vscode's search results:
image

**Comment by jesseduffield** [comment]
Two more changes I've made:
1) we now cache the files trie so that next time you search for a file it'll already have all the files loaded
2) once the files have loaded, the suggestions will refresh

Once these tests pass I'll merge

**Comment by screendriver** [comment]
Nice! Thank you very much! 🎉

**Comment by jesseduffield** [comment]
my pleasure :)

**Pull request merged**
