### PR TITLE
add commit files keybind to Keybindings_en.md

### PR DESCRIPTION
**Pull request by skanehira**

### CODE REVIEW

**Comment by jesseduffield** [comment]
if you add the following to the i18n english.go file (and the other i18n files):
```
		}, &i18n.Message{
			ID:    "CommitFilesTitle",
			Other: "Commit files",
```

and then run `go scripts/generate_cheatsheet.go`

This should generate the keybindings for you :)

**Comment by skanehira** [comment]
@jesseduffield 
I added to the i18n files and run scripts/generate_cheatsheet.go but it genereted the jp keybind only.

image

**Comment by jesseduffield** [comment]
ah, looks like it runs based off your language set in your env's LANG variable.

This patch should change the logic to generate the cheatsheet for each supported language (english, dutch, and polish).

```
diff --git a/scripts/generate_cheatsheet.go b/scripts/generate_cheatsheet.go
index f8beaa4..780ba92 100644
--- a/scripts/generate_cheatsheet.go
+++ b/scripts/generate_cheatsheet.go
@@ -25,16 +25,19 @@ type bindingSection struct {
 }
 
 func main() {
+	langs := []string{"pl", "nl", "en"}
 	mConfig, _ := config.NewAppConfig("", "", "", "", "", true)
-	mApp, _ := app.NewApp(mConfig)
-	lang := mApp.Tr.GetLanguage()
-	file, _ := os.Create("Keybindings_" + lang + ".md")
+	for _, lang := range langs {
+		os.Setenv("LC_ALL", lang)
+		mApp, _ := app.NewApp(mConfig)
+		file, _ := os.Create("Keybindings_" + lang + ".md")
 
-	bindingSections := getBindingSections(mApp)
+		bindingSections := getBindingSections(mApp)
 
-	content := formatSections(mApp, bindingSections)
+		content := formatSections(mApp, bindingSections)
 
-	writeString(file, content)
+		writeString(file, content)
+	}
 }
 
 func writeString(file *os.File, str string) {

```

**Comment by skanehira** [comment]
@jesseduffield 
>This patch should change the logic to generate the cheatsheet for each supported language (english, dutch, and polish).

Shall I add this?

**Comment by jesseduffield** [comment]
yes please do :)

**Comment by skanehira** [comment]
@jesseduffield 
I did :)

**Comment by jesseduffield** [comment]
merged :) Thanks for making this!

**Pull request merged**
