### PR TITLE
Clean up helix editor preset

### PR DESCRIPTION
**Pull request by jesseduffield**
- **PR Description**

See comments on https://github.com/jesseduffield/lazygit/pull/2668

- **Please check if the PR fulfills these requirements**

* [ ] Cheatsheets are up-to-date (run `go run scripts/cheatsheet/main.go generate`)
* [ ] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [ ] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [ ] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [ ] Docs (specifically `docs/Config.md`) have been updated if necessary
* [ ] You've read through your own file changes for silly mistakes etc

### CODE REVIEW

**Comment by stefanhaller** [comment]
Thanks for fixing these. It still needs an entry `"hx": "helix",` in the `editorToPreset` map though. (I would have pushed a fixup, but don't have time to check out the branch right now.)

**Comment by stefanhaller** [comment]
I pushed a fixup now. LGTM with that, thanks again!

And @dvic, sorry if my comments on #2668 came across as off-putting or nit-picky. I appreciate the contribution, thanks!

**Comment by jesseduffield** [comment]
Hmm I thought if I merged this to master locally and pushed master this PR would automatically close but it seams not. Alas

**Comment by dvic** [comment]
> I pushed a fixup now. LGTM with that, thanks again!
> 
> And @dvic, sorry if my comments on #2668 came across as off-putting or nit-picky. I appreciate the contribution, thanks!

No worries, thanks for taking the time to review PRs 👍

**Pull request closed without merging**
