### PR TITLE
add ability to customize time format in commit log

### PR DESCRIPTION
**Pull request by Ryooooooga**
```yaml
gui:
  timeFormat: 2006-01-02 15:04
```

スクリーンショット 2022-05-13 21 58 38

### CODE REVIEW

**Comment by jesseduffield** [comment]
Tested it and it works fine, though it's failing on CI

**Review by jesseduffield — CHANGES_REQUESTED** [review]
marking as changes requested for my own bookkeeping

**Comment by mark2185** [comment]
What about extending said formatting for other timestamps as well? E.g. `Local branches->Log`, `Commits->Patch`?

[Related issue.](https://github.com/jesseduffield/lazygit/issues/1953)

**Comment by jesseduffield** [comment]
One thing I think we should retain is the relative time used in the branches panel just because it doesn't take up much room and I think people would rather know e.g. 'I last checked this out 10m ago'

**Comment by Ryooooooga** [comment]
@jesseduffield I've fixed the test.

@mark2185 I think it would be good to be able to customize the commands displayed in the Patch panel, like `git.branchLogCmd`.

**Comment by jesseduffield** [comment]
🤩

**Pull request merged**
