### PR TITLE
lazyload sub-commits

### PR DESCRIPTION
**Pull request by Ryooooooga**
- **PR Description**

like https://github.com/jesseduffield/lazygit/pull/589

ref: https://github.com/jesseduffield/lazygit/issues/500#issuecomment-1425503789

スクリーンショット 2023-02-10 22 14 45

- **Please check if the PR fulfills these requirements**

* [x] Cheatsheets are up-to-date (run `go run scripts/cheatsheet/main.go generate`)
* [x] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [ ] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [x] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [x] Docs (specifically `docs/Config.md`) have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

### CODE REVIEW

**Comment by stefanhaller** [comment]
Oh nice, thanks. That was quick. 😄

I tested this, works well.

Or rather, it works as well as it does in the local commits panel, which is, I'd say, workable but not great. Our monorepo at work has 258560 commits; when typing `>` to go to the end, lazygit becomes unresponsive for several seconds. It seems that doing the work in chunks in the background would be a nice improvement.

**Comment by mark2185** [comment]
> workable but not great

Would you be willing to tackle the performance issue, maybe? 
There have been talks of how it shouldn't be _that_ slow, namely [gitui](https://github.com/extrawurst/gitui) eats up the `linux` repository for breakfast, yet `lazygit` struggles.

**Comment by stefanhaller** [comment]
> Would you be willing to tackle the performance issue, maybe?

Erm, not yet. 😄  I'm still only dabbling at hacking simple improvements here and there, still struggling with understanding the architecture, and I'm also very new to golang. And dayjob leaves very little time for open source engagement...

**Comment by Ryooooooga** [comment]
https://github.com/jesseduffield/lazygit/pull/2401 may help you.

**Comment by stefanhaller** [comment]
> https://github.com/jesseduffield/lazygit/pull/2401 may help you.

Actually it doesn't, unless I'm doing something stupid. With `order: 'default'` it's even slower in my quick tests, and memory consumption seems to be higher too. Not sure how to explain that.

Also, I really prefer topo order. 😄

**Comment by jesseduffield** [comment]
Sorry for taking a while to get around to this. Code looks good and it works fine from my local testing.

**Pull request merged**
