### PR TITLE
Commit message editor virtual space

### PR DESCRIPTION
**Pull request by sl4mmy**
Adds support for using the up & down arrow keys to dynamically resize the commit message window.

### CODE REVIEW

**Comment by sl4mmy** [comment]
This is my initial spike of using the arrow keys to resize the commit message window.  It's definitely not ready to be committed yet but I want to get feedback on the idea.

Pressing the down arrow key when the cursor is on the last line of the commit message window adds a new line.

Pressing the up arrow key when the cursor is on the last line of the commit message window checks if the last line is blank, and if so removes the entire line.

**Comment by sl4mmy** [comment]
@jesseduffield I know you mentioned in a comment on #28 that you prefer single-line comments but would you be opposed to making the commit message window multiline by default?  That is, when the pop-up window opens it is always large enough to display several lines?  Of course, users would still be allowed to only use the first-line if they wish.

If you're not opposed to it then I will invest some time in spiking out some other features I'd like to see for the commit message window, such as support for templates, autocomplete, etc.

**Comment by jesseduffield** [comment]
@sl4mmy sorry for my late response! I'm fine with the commit message panel being multiple lines by default

**Comment by theduke** [comment]
Is `<tab>` supposed to work at the moment for adding a newline to the commit?

This is currently not working for me. (lazygit 0.29)

**Comment by jesseduffield** [comment]
Closing due to staleness (and because we now have a keybinding for adding a newline)

**Pull request closed without merging**
