### PR TITLE
Format code to pass lint

### PR DESCRIPTION
**Pull request by black-desk**
hope it works

### CODE REVIEW

**Comment by black-desk** [comment]
Yeah!

**Comment by mjarkk** [comment]
Do you have documentation on the `go:build` comments it doesn't seem to break anything but i'm not sure why go fmt wants it.

**Comment by black-desk** [comment]
> Do you have documentation on the `go:build` comments it doesn't seem to break anything but i'm not sure why go fmt wants it.

try run `find . ! -path "./vendor/*" -name "*.go" -exec gofmt -s -d {} \;`

You will find out gofmt really wants this. I have no idea too :)

**Comment by fsmiamoto** [comment]
This is a new change from Go 1.17 that makes `gofmt` enforce the new style of build constraints - https://golang.org/doc/go1.17#vet

The rational of the changes is explained here: https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md
> If a file contains only // +build lines, gofmt will add an equivalent //go:build line above them.

We should be good with this one

**Comment by fsmiamoto** [comment]
But I guess this shows that maybe we should consider pinning the `go` version on the Lint workflow.
At least for me, it can be really annoying having to dig through Go changes unexpectedly.

**Comment by mjarkk** [comment]
@fsmiamoto thanks for the information!  
I'll merge this for now so we can keep running the last go version

**Comment by mjarkk** [comment]
@fsmiamoto i agree these unexpected linting errors are annoying but personally i would prefer always linting the code with the latest go version.
This overcomes that a user running the latest go version has a different result when trying to simulate why the ci linting failed locally.

**Pull request merged**
