### PR TITLE
bump gocui

### PR DESCRIPTION
**Pull request by jesseduffield**
fixes https://github.com/jesseduffield/lazygit/issues/465

### CODE REVIEW

**Comment by dawidd6** [comment]
`test.sh` seems to run just fine on my machine.

Using Go 1.13.

**Comment by jesseduffield** [comment]
it ran fine on my machine as well but failed on CI

**Comment by dawidd6** [comment]
One thing is that `test.sh` does not have `-mod=vendor` in arguments to `go test` and it pulls all deps.

**Comment by jesseduffield** [comment]
ahh do you reckon that's the cause?

**Comment by dawidd6** [comment]
Yep, tested it in Docker.

**Comment by jesseduffield** [comment]
awesome, this build should work then

**Comment by dawidd6** [comment]
heh, but it doesn't

can you try this: https://github.com/jesseduffield/lazydocker/commit/817fb5349b7535af73a37490c3fa1330d36b2a5d

**Comment by dawidd6** [comment]
you might also want to delete `go.sum` and run `go mod tidy` to fix this checksum error

**Comment by jesseduffield** [comment]
done! thanks for the help @dawidd6 :)

**Pull request merged**
