### PR TITLE
fix chinese translate

### PR DESCRIPTION
**Pull request by btwise**

### CODE REVIEW

**Review by mjarkk — CHANGES_REQUESTED** [review]
I'm not going to merge this unless @black-desk says so.
I got a bit worried by a comment on an earlier commit from you so i pass this one https://github.com/jesseduffield/lazygit/commit/a13e919d3d4184de0ffed55019ec8c0e510bae86#commitcomment-56416028

**Comment by mjarkk** [comment]
@black-desk also opened a PR to fix the translations https://github.com/jesseduffield/lazygit/pull/1473 lets merge that code first

**Comment by black-desk** [comment]
> @black-desk also opened a PR to fix the translations #1473 let's merge that code first

What makes me surprised is that this guy basically just copying my in-progress works to this PR few days ago. I have no idea why he(she?) doing this.

**Comment by mjarkk** [comment]
Ah in that case i'll close this PR

**Comment by btwise** [comment]
> > @black-desk还打开了一个 PR 来修复翻译#1473让我们先合并该代码
> 
> 让我惊讶的是，这家伙基本上只是将我正在进行的

> > @black-desk also opened a PR to fix the translations #1473 let's merge that code first
> 
> What makes me surprised is that this guy basically just copying my in-progress works to this PR. I have no idea why he(she?) doing this.

Don't mind, I just saw that your submission didn't pass the automatic compilation, so I tried a few more times, but still didn't pass the automatic check, your translation is good

**Comment by black-desk** [comment]
> Don't mind, I just saw that your submission didn't pass the automatic compilation, so I tried a few more times, but still didn't pass the automatic check, your translation is good

#1479

**Pull request closed without merging**
