### PR TITLE
added edit and changed open, removed sublime and vsCode

### PR DESCRIPTION
**Pull request by maiterth**
Hey,
this is my first stab at golang, so this might be not optimal code.
But it solves the "open" issues.

Also I think moving from sublime and vscode are ok.
If people have set them in their open command ok, if the want to edit them open an editor instead.

I'm not sure that the subcommands are handled properly though.

### CODE REVIEW

**Comment by maiterth** [comment]
The pull request is actually intended for #18

**Comment by jesseduffield** [comment]
hey man thanks for the PR. I still got the glitchiness issue after returning from the subprocess i.e. when switching panels random characters start showing up around the screen. I've adapted your code here into my PR at https://github.com/jesseduffield/lazygit/pull/18/files and I've got it basically working but with some big tradeoffs. I found that I had to start another Gui after the subprocess returns to get it to work, and that if I closed the first Gui at all, I wasn't able to exit the application for some reason.

Please let me know if I've understood your code correctly in my minor refactor. And it would be great if we (or anybody else watching) could find out what needs to be changed so that we can get subprocesses working without needing to close/reinitialize the main Gui

**Comment by maiterth** [comment]
Looks fine to me :+1:  
The idea is there. The only thing is that there is always to call to which, perhaps that can be memoized.

**Comment by jesseduffield** [comment]
Yeah memoization is a good idea. But I still don't think it's a good enough solution to reinitialize the Gui everytime we run a subprocess, as is the case in this PR  and my one https://github.com/jesseduffield/lazygit/pull/18. There are memory considerations and, while the code stands as it is without even closing the initial Gui, potential for lots of bugs. I'm not sure what needs to be done in the runSubprocess function to do it properly

**Comment by jesseduffield** [comment]
For now we've gone with the reinitialize Gui approach, so I'm closing this PR :)

**Pull request closed without merging**
