### PR TITLE
Rebase on currently selected branch reworked

### PR DESCRIPTION
**Pull request by mark2185**
Rebase on the upstream branch by default

- **PR Description**

- **Please check if the PR fulfills these requirements**

* [x] Cheatsheets are up-to-date (run `go run scripts/cheatsheet/main.go generate`)
* [x] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [x] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [x] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [x] Docs (specifically `docs/Config.md`) have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

### CODE REVIEW

**Comment by mark2185** [comment]
Instead of throwing an error when pressing `r` on the currently checked out branch, we offer the rebase to the upstream of the current branch.

In case the branch has no upstream, the old error message "Cannot rebase onto itself" is displayed.

Just a small QoL improvement

**Comment by jesseduffield** [comment]
I'm undecided on this: I like the idea of instead having the user press 'u' to see the options related to the upstream and then choose to rebase onto the upstream from there. That's a pattern that supports rebasing onto _any_ upstream (not just the checked out one). Having the existing 'r' keybinding change its behaviour based on which branch you've got selected sounds like it could cause confusion

**Comment by mark2185** [comment]
> Having the existing 'r' keybinding change its behaviour based on which branch you've got selected sounds like it could cause confusion

Well, currently `r` tries rebasing onto the selected branch, so it's not like this is a completely new behavior, just in this special case instead of erroring out we'll bring up a menu with what the user _probably_ wanted. 

Lucky for all of us it's a menu, so it needs confirmation.

I guess this is the classic crossroad in UX between "having reasonable and sensible defaults for new users" and "having mappings for people who have used it for a while who are okay with shooting themselves in the foot at lightspeed".

IIRC you'd prefer accessibility for newcomers.

I'm okay with this being rejected, I'll keep it since I'm building locally anyways :)

**Comment by jesseduffield** [comment]
I should have been clearer: I didn't mean it could cause confusion for existing users, I meant it could cause confusion for any user, given that 'r' means rebase onto the selected branch generally. I suppose users could get used to having 'r' mean 'rebase onto upstream' when applied to the checked-out branch, but given that we have a use-case for rebasing onto any upstream, I'd rather we just find a good UX for that rather than introduce an inconsistency in the UX.

I will often attempt to delete a branch, forgetting that it's the currently checked out branch. I much prefer in that case to just see an error message telling me I can't delete the checked out branch. So I'm applying that same intuition to the case of rebasing.

Let's close this off and continue further discussion over at https://github.com/jesseduffield/lazygit/issues/2938

**Pull request closed without merging**
