### PR TITLE
Fix refreshing custom patch view when adding first file to custom patch

### LINKED ISSUE #3258: Refreshing custom patch view when adding commit files to custom patch
**Describe the bug**
When adding a commit file to a custom patch, the bottom part of the right half displays title "Diff" and is empty. The view updates after hitting an arrow key to navigate to another file. Something is not refreshing properly when files are added to the patch builder.

**To Reproduce**

1. Navigate to the commits context
2. Hit enter to view files in a commit
3. Hit space to add file to custom patch

**Expected behavior**
Immediately after adding a commit file to the patch builder, the view should update as in the "post-refresh" screenshot below.

**Screenshots**
Pre-refresh:
pre-refresh

Post-refresh:
post-refresh

**Version info:**
This happens on current master (05b97c8c), but does not happen on 0.40.2. I'm able to duplicate on macOS, Windows 11, and Ubuntu 22.04 (WSL).

**Additional context**
Doing a git bisect, it looks like this behavior started after 240948b8. This change on my fork (https://github.com/afhoffman/lazygit/commit/d1f1ed0c28e686f24e655aaf4d2837972a8b2517) seems to fix it but I'm not totally sure why that fix works, and it doesn't feel right.

### PR DESCRIPTION
**Pull request by stefanhaller**
Fixes #3258.

### CODE REVIEW

**Comment by stefanhaller** [comment]
I can't say I'm super happy with this fix. It is straightforward and fixes the problem reliably, but I have the feeling there might be a cleaner way to solve it. But I don't understand the logic around when views are made visible or invisible well enough to change anything there, so for now I'd propose to go with this.

Also, I tried adding a test that demonstrates the issue, but failed: when adding an assertion like `t.Views().Secondary().Content(Contains("whatever"))`, it succeeded without the fix, presumably because the view's content was actually correct, it's just that the view wasn't visible, which I don't think we can test. Let me know if I'm missing a way to do that.

Finally, I labelled this as "ignore-for-release" rather than "bug", since it fixes a regression that was only introduced after the last release.

**Comment by afhoffman** [comment]
I can confirm this fix is working for me too. I also rebased a local copy of #3259 on top of this, and that works too. Thanks!

**Comment by jesseduffield** [comment]
I agree this is awkward but I can't think of a better approach and it makes sense to me: in one case we care about what's visible in a window, and in another case we care about which view is on top of a window which is itself invisible. We don't have a concept of of an invisible window so instead we just have each view inside a window being invisible, and that's what makes this awkward. We could introduce an IsWindowVisible function to the window helper and then use that in tandem with TopViewInWindow (removing the view.Visible check in that function) to support both cases, though I'm not 100% sure if you can rely on all views of a window being either visible or invisible together.

> Also, I tried adding a test that demonstrates the issue, but failed: when adding an assertion like t.Views().Secondary().Content(Contains("whatever")), it succeeded without the fix, presumably because the view's content was actually correct, it's just that the view wasn't visible, which I don't think we can test. Let me know if I'm missing a way to do that.

There is an IsVisible() method in `pkg/integration/components/view_driver.go` which sounds like the thing you want

**Review by jesseduffield — APPROVED** [review]

**Comment by stefanhaller** [comment]
> There is an IsVisible() method in `pkg/integration/components/view_driver.go` which sounds like the thing you want

That doesn't help either, but I don't have time to investigate why right now. Merging without a test...

**Pull request merged**
