### PR TITLE
Expand home dir

### PR DESCRIPTION
**Pull request by Mo8it**
Fix issues like https://github.com/jesseduffield/lazygit/issues/2001

See comment https://github.com/jesseduffield/lazygit/issues/2001#issuecomment-1165582168

### CODE REVIEW

**Comment by Ryooooooga** [comment]
Expanding `~` is the responsibility of the shell, not lazygit.

The original issue was caused by an incorrect configuration (it should be `"$HOME/.config/lazygit/config.yml"`, not `"~/.config/lazygit/config.yml"`), and it is a deviation from common UNIX program behavior for lazygit to expand `~`.

**Comment by Mo8it** [comment]
But it does not cause any harm, right?

**Comment by Ryooooooga** [comment]
We should not do what we do not have to do.

**Comment by Mo8it** [comment]
Alright, you decide.
But if you don't want to include it, please add a small hint to the docs to the config paths :)

I have no problem with closing the PR.

**Comment by jesseduffield** [comment]
I agree with @Ryooooooga: the less complexity we can have in lazygit, the better. With that said, if over time we see others running into this same problem, we can reconsider. Thanks for raising the PR at any rate @Mo8it :)

**Pull request closed without merging**
