### PR TITLE
add chinese for i18n

### PR DESCRIPTION
**Pull request by btwise**
@jesseduffield 
Added localization support for Chinese users, hope to merge!

### CODE REVIEW

**Comment by mjarkk** [comment]
Thanks!
As i can't read Chinese, Is there anyone who wants to do a quick check over the changes to see if they are approprite?

**Comment by jack9603301** [comment]
It seems that this is just a translation of the text. I may not know about this project for the moment, but it should not be a big problem

Just need to translate English text into Chinese, there are a lot of tools to do it

**Comment by mjarkk** [comment]
@jack9603301 Thanks for checking!

@btwise It seems like the pipeline is failing

**Comment by btwise** [comment]
> @jack9603301 Thanks for checking!
> 
> @btwise It seems like the pipeline is failing

What's the problem?

**Comment by btwise** [comment]
> It seems that this is just a translation of the text. I may not know about this project for the moment, but it should not be a big problem
> 
> Just need to translate English text into Chinese, there are a lot of tools to do it

It's a simple job, but something is better than nothing

**Comment by mjarkk** [comment]
The cd/ci is failing over your changes, see: https://github.com/jesseduffield/lazygit/pull/1320/checks?check_run_id=2619261757

**Comment by jesseduffield** [comment]
I took the liberty of fixing the formatting issue: was just a matter of running `gofmt`

**Comment by jesseduffield** [comment]
Thanks for making this @btwise !

**Pull request merged**
