### PR TITLE
Extend icon coverage on remotes and file extensions

### LINKED ISSUE #3426: Extend Nerd Fonts icon coverage on more remotes and file extensions
As noted in the CONTRIBUTING file I open this issue before doing any change.

**Is your feature request related to a problem? Please describe.**
- _I'm always frustrated when_ I'm on the remote branches tab and the icon used is a square for remotes that are not included.
  -  **Arch Linux** (https://gitlab.archlinux.org): Hosting their tools, mirrors, etc. Merge requests and Issues will be open to users in the foreseeable future.
  -  **freedesktop.org** (https://gitlab.freedesktop.org): Software focused on interoperability and shared technology for open-source graphical and desktop systems.
  -  **GNOME** (https://gitlab.gnome.org): Software from GNOME project.
  -  **Codeberg** (https://codeberg.org): Collaboration platform providing Git hosting and services for free and open source software, content and projects. .
  -  **Debian** (https://salsa.debian.org) Repository of Debian.
  -  **FreeBSD** (https://cgit.freebsd.org): FreeBSD project.
  -  **GNU** (https://www.gnu.org): GNU packages.
  -  **KDE** (https://invent.kde.org): Software from GNOME project.
  -  **Linux** (https://kernel.org/): The Linux kernel projects.
  -  **sourcehut** (https://sr.ht), independent git hosting site.
- _I'm always frustrated when_ some file extensions don't have an associated icon.

image

**Describe the solution you'd like**
- Add various _popular_ remotes to Lazygit, previous list would be nice =)
- Associate more icons to _popular_ file extensions.

**Describe alternatives you've considered**
- The first option is to incorporate all these changes in the code
- Another option is to create a config file that enables the user to add custom pairs of remotes url/file extensions and icons via config file.

**Additional context**
- I have no Go experience but reading the code I can figure it out how to make the changes to add icons but not how to implement feature via config file.
- Please, see the example of _powerlevel10k_ for the remotes and the example of _eza_ for the file extensions I'm interested on https://github.com/lukas-w/font-logos/issues/130

### Extra comment

In the previous version the color for unstaged files covered status, icon and filename but now with recent update filenames seems to use default foreground color, the icons are colored even if they are not staged, leaving only the status with the "unstaged color". I think would be better to make all use the unstaged color as before and only change the icon color when the files is (partially) staged. Otherwise I think they distract a little.

image

I would love to have this changes on lazygit, **do you think that are a good adition?** If so to start on this unless you have some plans, would love to know.

### PR DESCRIPTION
**Pull request by hasecilu**
- **PR Description**

Initially I opened #3426 issue, this PR is targeted to fix that.

- **Please check if the PR fulfills these requirements**

* [X] Cheatsheets are up-to-date (run `go generate ./...`)
* [X] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [ ] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [X] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [X] Docs (specifically `docs/Config.md`) have been updated if necessary
* [X] You've read through your own file changes for silly mistakes etc

This is the result from the remote icons that I posted on the issue.
Note: The FreeBSD only is triggered if the remote is "git.FreeBSD.org", note the capitalization

Edit: btw, there are also icons for gitea -> `nf-linux-gitea`, \uf339,  and forgejo -> `nf-linux-forgejo`, \uf335,  if someone is interested on some instances that use that sofware.

image

Would be nice if in the future the user can make overrides via config file.
```yml
icon_overrides:
  filenames:
    Cargo.toml: 🦀
    Cargo.lock: 🦀
  extensions:
    rs: 🦀
    nix: ❄
```

Fix #3426

### CODE REVIEW

**Review by jesseduffield — APPROVED** [review]
LGTM, great work

**Comment by jesseduffield** [comment]
@hasecilu sorry for the late reply: the answer is yes, that would be good

**Comment by ynhhoJ** [comment]
@jesseduffield , do you think that in the next updates / future it will be possible to associate custom icons with file types / file names?

@hasecilu , https://github.com/DaikyXendo/nvim-material-icon - has more icons than [nvim-web-devicons](https://github.com/nvim-tree/nvim-web-devicons)

**Comment by hasecilu** [comment]
> will be possible to associate custom icons with file types / file names?

If you refer to specify the whole name of a file that0s already implemented, you need to use `var nameIconMap`, or do you refer to something more complex as specifying directory and names?

> @hasecilu , https://github.com/DaikyXendo/nvim-material-icon - has more icons than [nvim-web-devicons](https://github.com/nvim-tree/nvim-web-devicons)

I'll check it.

**Comment by hasecilu** [comment]
Rebased and added some new icons.

`nvim-material-icons` project have a very extensive list of associations. Potentially would be about 1300 icon associations more, here is a file showing them: <https://github.com/hasecilu/lazygit/blob/test/extensive_icon_list/pkg/gui/presentation/icons/file_icons2.go>. A lot of them are quite repetitive for which a better strategy would be pattern matching. What do you think?

**Comment by jesseduffield** [comment]
> nvim-material-icons project have a very extensive list of associations. Potentially would be about 1300 icon associations more, here is a file showing them: [hasecilu/lazygit@test/extensive_icon_list/pkg/gui/presentation/icons/file_icons2.go](https://github.com/hasecilu/lazygit/blob/test/extensive_icon_list/pkg/gui/presentation/icons/file_icons2.go?rgh-link-date=2024-07-08T18%3A53%3A36Z). A lot of them are quite repetitive for which a better strategy would be pattern matching. What do you think?

That would be great. I don't think pattern matching is necessary or desirable: using a string key is going to be much faster.

At any rate I'll merge this PR as-is

**Pull request merged**
