### PR TITLE
Allow to choose Nerd fonts versions

### PR DESCRIPTION
**Pull request by bmichotte**
- **PR Description**
Following the PR #2604, I added a `nerdFontsVersion` option which allows you to choose the version of the Nerd Fonts you have. I defaulted it to 2.

I discovered Go this morning, so please feel free to help me to have the code "Go-compliant" :D

- **Please check if the PR fulfills these requirements**

* [X] Cheatsheets are up-to-date (run `go run scripts/cheatsheet/main.go generate`)
* [X] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [ ] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
No new tests or update needed (I guess)
* [ ] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
N/A
* [X] Docs (specifically `docs/Config.md`) have been updated if necessary
* [X] You've read through your own file changes for silly mistakes etc

### CODE REVIEW

**Comment by stefanhaller** [comment]
Thanks for working on this! You beat me to it, I was also just about to open a PR. Since I was almost done, I decided to publish my PR as well, so we can choose which approach we like better. I decided to patch the icon tables for v2; while it doesn't really feel great to patch tables that are conceptually const, it makes the code that works with the tables much simpler. See #2731.

One thing that's missing from your PR is deprecating the `showIcons` config and using it only as a fallback when `nerdFontsVersion` is unset.

**Comment by stefanhaller** [comment]
> > One thing that's missing from your PR is deprecating the showIcons config and using it only as a fallback when nerdFontsVersion is unset.
> 
> I chose to not deprecate it and keep it possible to either choose to display the icons or not as well as choosing version 2 or 3. Both way are valid imo.

Jesse explicitly proposed deprecating it [here](https://github.com/jesseduffield/lazygit/pull/2604#issuecomment-1543586440), so I thought it makes more sense to follow that suggestion.

**Comment by jesseduffield** [comment]
I'm going with https://github.com/jesseduffield/lazygit/pull/2731 over this one because it has the deprecation logic in it and it has fewer touch points, but thanks for making this PR anyway, I appreciate the non-mutative approach. I hope this doesn't dissuade you from contributing to Lazygit in the future!

**Comment by bmichotte** [comment]
> I hope this doesn't dissuade you from contributing to Lazygit in the future!

@jesseduffield Absolutely not, to be honest, IDC that you have chosen #2731 over mine, I'm just happy that the functionality made it to `main` 👍

**Pull request closed without merging**
