### PR TITLE
Internationalise logging of commands

### PR DESCRIPTION
**Pull request by KarlHeitmann**
- **PR Description**

These code changes addresses #2848 

I took the example @jesseduffield left on that issue and took that as a starting point to do the rest of the code changes.

I am not yet so familiar with lazygit and its features, so I don't know how to trigger all the places that logs the hard coded messages. I have reviewed my code changes and I ~ think ~ that I have not made any silly mistake. But a second pair of eyes would be very helpful, please review the changes with attention because I mostly relied here on linter and compiler (have compiled the code and it works)

The name of the i18n strings may be better. Any suggestion is welcome.

Note that I've added the `Log` suffix to all the new strings defined in `pkg/i18n/english.go` and named the strings ~ like ~ the function that calls it. Would it be better to add a namespace for these king of log strings? Since you have an [Actions](https://github.com/jesseduffield/lazygit/blob/7cfbfb7183934dd9c2106dc7b521a7e1d6419741/pkg/i18n/english.go#L605) namespace, a [Bisect](https://github.com/jesseduffield/lazygit/blob/7cfbfb7183934dd9c2106dc7b521a7e1d6419741/pkg/i18n/english.go#L585C6-L585C12) namespace, etc. Would it be better to add a `Log` namespace for this purpose? Any other suggestion is welcome.

- **Please check if the PR fulfills these requirements**

* [x] Cheatsheets are up-to-date (run `go run scripts/cheatsheet/main.go generate`)
* [x] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [x] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [x] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [x] Docs (specifically `docs/Config.md`) have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

### CODE REVIEW

**Comment by jesseduffield** [comment]
Great work @KarlHeitmann . I agree with your suggestion to add a Log namespace. Let's do that.

**Comment by KarlHeitmann** [comment]
Ready @jesseduffield 
- [x] Created `Log` namespace for log related strings to be translated in i18n, moved translations strings there
- [x] Added the fmt.Sprintf hard coded translation string added by @stefanhaller on pr #2835 

Let me know if there is something else to do here.

**Comment by jesseduffield** [comment]
@KarlHeitmann nice one

**Comment by KarlHeitmann** [comment]
Anytime @jesseduffield ! looking forward to send more PRs. I want to practice Go language.

**Comment by jesseduffield** [comment]
For sure, feel free to take a look at other issues and see if anything interests you. Feel free to ask for clarification on anything

**Pull request merged**
