### PR TITLE
Add NixOs installation instructions to README.md

### PR DESCRIPTION
**Pull request by rsniezek**
Extend README.md with instructions on how to try and install the lazygit on NixOs.

- **PR Description**
Just README.md update, no code changes.

- **Please check if the PR fulfills these requirements**

* [ ] Cheatsheets are up-to-date (run `go generate ./...`)
* [ ] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [ ] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [ ] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [x] Docs (specifically `docs/Config.md`) have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

### CODE REVIEW

**Comment by karimkhaleel** [comment]
From my limited knowledge of nix and NixOS, this checks out.

**Comment by stefanhaller** [comment]
OK, thanks. I'm happy to merge this, but please don't merge master into your branch. This creates a messy git history that we don't want here. Rebase onto master instead.

(It's not possible to fix this now within lazygit because it insists on using the `--rebase-merges` option when you rebase, but you can fix it on the command line by saying `git rebase --no-rebase-merges master`.)

**Comment by rsniezek** [comment]
> OK, thanks. I'm happy to merge this, but please don't merge master into your branch. This creates a messy git history that we don't want here. Rebase onto master instead.
> 
> (It's not possible to fix this now within lazygit because it insists on using the `--rebase-merges` option when you rebase, but you can fix it on the command line by saying `git rebase --no-rebase-merges master`.)
Done. Added also the nix-flake enabled way to the readme. Cheers!

**Comment by stefanhaller** [comment]
Nice, thanks. I took the liberty of force-pushing again to remove a trailing space (I'm picky about things like this...)

**Comment by rsniezek** [comment]
> Nice, thanks. I took the liberty of force-pushing again to remove a trailing space (I'm picky about things like this...)

No issue, your playground, your rules :)

Thanks for merging

**Pull request merged**
