### PR TITLE
Just spotted some small typos in NL translation

### PR DESCRIPTION
**Pull request by Alpakash**
I'm learning the LazyGit keybindings right now. Spotted some minor typos in the nl translation

### CODE REVIEW

**Comment by mjarkk** [comment]
LGTM

**Review by mjarkk — CHANGES_REQUESTED** [review]
This file is generated.  
You'll need to change these in `pkg/i18n/dutch.go`  
After editing the file you'll need to execute `scripts/generate_cheatsheet.go` to update `docs/keybindings/Keybindings_nl.md`

**Comment by jesseduffield** [comment]
Looks like we haven't done a very good job making it clear that those files are auto-generated. I've made a PR to make it clearer so that there's less confusion in future :)

https://github.com/jesseduffield/lazygit/pull/1652

**Comment by jesseduffield** [comment]
I've also changed the command to `go run scripts/cheatsheet/main.go generate`

**Review by mjarkk — APPROVED** [review]

**Review by Alpakash — COMMENTED** [review]
I've edited the suggested changes in this PR

**Comment by Alpakash** [comment]
I get an CI error for check-cheatsheet. I did generate the (translated).md files with the `go run scripts/cheatsheet/main.go generate` command.

**Comment by jesseduffield** [comment]
@Alpakash looks like the cheatsheet generator was playing up because of your config setting the language manually. I've fixed up that script so that shouldn't be a problem anymore and I've taken the liberty to run the script myself.

**Pull request merged**
