### PR TITLE
Add icon for Kotlin files

### PR DESCRIPTION
**Pull request by pereBohigas**
- **PR Description**

Icon for files with Kotlin file extension ([`.kt`](https://docs.fileformat.com/programming/kt/)) is being added here.

- **Please check if the PR fulfills these requirements**

* [x] Cheatsheets are up-to-date (run `go run scripts/cheatsheet/main.go generate`)
* [x] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [x] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [x] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [x] Docs (specifically `docs/Config.md`) have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

### CODE REVIEW

**Comment by Ryooooooga** [comment]
please add kts too

**Comment by pereBohigas** [comment]
Now extended to Kotlin scripting files

**Comment by paulwyszynski** [comment]
Very nice 👏

**Comment by paulwyszynski** [comment]
@Ryooooooga can you approve? 😀

**Comment by jesseduffield** [comment]
@pereBohigas thanks for making this :)

**Pull request merged**
