### PR TITLE
Add 'tag' in push tag command 

### LINKED ISSUE #2546: Fail to push a tag that has the same name as the branch
**Describe the bug**
When trying to push a tag to remote that has the same branch name, it will fail with:
```
error: src refspec <tag name> matches more than one
error: failed to push some refs to <Remote git url>
```
Because it is using the command `git push <remote> <tag name>`, which doesn't specify it is pushing a tag.

**To Reproduce**

1. Create a branch with an arbitrary name and push to remote
2. Go to tag tab and create a tag with the same name as you created the branch
3. Push the tag

**Expected behavior**
Tag should be pushed

**Screenshots**
None for now, can provide one if failed to reproduce.

**Version info:**
_Run `lazygit --version` and paste the result here_
```
commit=v0.36.0, build date=2022-11-15T07:26:07Z, build source=binaryRelease, version=0.36.0, os=linux, arch=amd64, git version=2.38.1
```
_Run `git --version` and paste the result here_
`git version 2.38.1`

**Additional context**
None for now.

**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.

Check code below, don't think it matters but can do so later if needed.

https://github.com/jesseduffield/lazygit/blob/82c54ed3d2339d2653dd8d06a39bcfb0d5e6cbe0/pkg/commands/git_commands/tag.go

```diff
func (self *TagCommands) Push(remoteName string, tagName string) error {
- return self.cmd.New(fmt.Sprintf("git push %s %s", self.cmd.Quote(remoteName), self.cmd.Quote(tagName))).PromptOnCredentialRequest().WithMutex(self.syncMutex).Run()
+ return self.cmd.New(fmt.Sprintf("git push %s tag %s", self.cmd.Quote(remoteName), self.cmd.Quote(tagName))).PromptOnCredentialRequest().WithMutex(self.syncMutex).Run()
}
```

See https://stackoverflow.com/a/52063091

### PR DESCRIPTION
**Pull request by AKARSHITJOSHI**
- **PR Description**
Fix issue by adding the correct git command as per https://stackoverflow.com/a/52063091
Fixes #2546

### CODE REVIEW

**Comment by Neko-Box-Coder** [comment]
@AKARSHITJOSHI  Is the CI error related to #2550?

**Comment by stefanhaller** [comment]
It looks like it, yes. Try rebasing onto master and force-pushing.

**Comment by Neko-Box-Coder** [comment]
Is there anything else missing from the PR? 
If not it will be nice to get it merged so that I can get it in next version :)

**Comment by jesseduffield** [comment]
Thanks for making this @AKARSHITJOSHI

**Pull request merged**
