### PR TITLE
Make it easy to create "amend!" commits

### PR DESCRIPTION
**Pull request by stefanhaller**
- **PR Description**

To support this, we turn the confirmation prompt of the "Create fixup commit" command into a menu; creating a fixup commit is the first entry, so that "shift-F, enter" behaves the same as before. But there are additional entries for creating "amend!" commits, either with or without file changes. These make it easy to reword commit messages of existing commits.

- **Please check if the PR fulfills these requirements**

* [x] Cheatsheets are up-to-date (run `go generate ./...`)
* [x] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [x] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [x] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [x] Docs (specifically `docs/Config.md`) have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

### CODE REVIEW

**Review by jesseduffield — APPROVED** [review]
Awesome, LGTM

**Comment by bb** [comment]
Hi! I'm late to the party, just found this thanks to the recent release. You might want to have a look at [git-absorb](https://github.com/tummychow/git-absorb) which I've been using for that. Their _commute_ approach might allow adds without corresponding removes if they're adjacent.

**Comment by stefanhaller** [comment]
That's very interesting, thanks. I'll play with that and see if it works better than our approach.

**Comment by stefanhaller** [comment]
@bb You may want to have a look at #3602, which supports hunks with only added lines now.

I now had a chance to have a very close look at how git-absorb works, and I do indeed think that our `ctrl-f` works better in many cases (after the enhancement of #3602, that is). If you are interested, you might have a read at [this document](https://github.com/jesseduffield/lazygit/blob/e726ac423cc89c29c88599982f2a0203c87e0901/docs/dev/Find_Base_Commit_For_Fixup_Design.md), where I tried to describe the differences.

**Comment by bb** [comment]
Thank you ❤️, I'll have a look!

**Pull request merged**
