### PR TITLE
Fix checking for credentials performance

### PR DESCRIPTION
**Pull request by mark2185**
None of the patterns spill over multiple lines so if we haven't matched the output so far, and we have received a newline, we can disregard everything before the last newline.

Also it's faster if we compile the `regex` patterns ahead of time instead of compiling them just in time because that's what `regexp.MatchString` was doing internally.

I know the sample size is 1, but I've tried fetching `970` commits (from `v0.32` to current `master`) and it cuts down from `>35mins` (that's when I gave up looking at the stopwatch) on `master` to `5s` on this branch.

- **PR Description**

There is the issue of the `Command Log` being cut off, but I'm not entirely sure if that's caused by this PR. I'll leave the current `master` fetch running to see if it results in the same thing.

image

- **Please check if the PR fulfills these requirements**

* [x] Cheatsheets are up-to-date (run `go run scripts/cheatsheet/main.go generate`)
* [x] Code has been formatted (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#code-formatting))
* [x] Tests have been added/updated (see [here](https://github.com/jesseduffield/lazygit/blob/master/pkg/integration/README.md) for the integration test guide)
* [x] Text is internationalised (see [here](https://github.com/jesseduffield/lazygit/blob/master/CONTRIBUTING.md#internationalisation))
* [x] Docs (specifically `docs/Config.md`) have been updated if necessary
* [x] You've read through your own file changes for silly mistakes etc

### CODE REVIEW

**Comment by mark2185** [comment]
>  I'll leave the current `master` fetch running to see if it results in the same thing.

I chickened out after an hour and a half because the fans were getting annoying.

**Comment by jesseduffield** [comment]
Awesome work! I've tested locally pulling 300 commits and it's pretty fast.

Could you add a test or two for the processOutput() method? Should just be a matter of passing in a reader, writer, and a promptUserForCredential function and then asserting that we've written the expected password to the writer.

**Comment by stefanhaller** [comment]
I just happened to run into this problem yesterday. Pulled master, output of `git pull` was 2500 lines, took *forever*.

Any news on this? (No pressure, just asking 😄) It would be cool to get this merged soon, my co-workers also run into it all the time.

(Just to be clear, the number of commits you pull has nothing to do with it, it's the number of file changes that matter; it could be just one commit that touches a lot of files. So in repositories with lots of code churn it's more likely to happen often. That's the case for us at work.)

**Comment by mark2185** [comment]
I'll try to set some time aside to write the tests today, forgot about it because I use this branch for building manually :)

**Comment by stefanhaller** [comment]
Yes, now that I found it I also use it locally. Just took me a while to find it, but now I learned how to profile in go, so also a good thing. 😄

**Comment by mark2185** [comment]
> Should just be a matter of passing in a reader, writer, and a promptUserForCredential function and then asserting that we've written the expected password to the writer.

Could you (or anyone else) give me a few more pointers? 
I need a `cmdObjRunner` to test it, and it requires a `logrus.Entry` and a `guiIO`, but that seems a tad overkill for testing `runAndDetectCredentialRequest`. 
Or should I go and upgrade the `fake_cmd_obj_runner` for it, but that also sorta kinda seems out of scope?

What other ways are there to test class methods?

**Comment by stefanhaller** [comment]
> I need a cmdObjRunner to test it, and it requires a logrus.Entry and a guiIO, but that seems a tad overkill for testing runAndDetectCredentialRequest.

I see `NewDummyLog()` and `NewNullGuiIO()`, sounds like these would help?

**Comment by jesseduffield** [comment]
@mark2185 to nudge this PR along I've taken the liberty of adding a couple tests. I'll leave it to you to add any other tests that speak to edge cases in the new code, then we can merge and put this bug behind us :)

**Comment by mark2185** [comment]
Aw shucks, thanks for that. 

I'll try Stefan's tactic for my next PR, first write the (failing) tests, and then the fix, maybe that'll help me get it done.

As for edge case tests - I don't think we've had any, the output being cut off at the end might be worth looking into if anyone else has ever encountered it.

**Comment by jesseduffield** [comment]
Alright let's merge then

**Pull request merged**
