### PR TITLE
WIP: Custom Pagers

### PR DESCRIPTION
**Pull request by jesseduffield**
image

image

The original use case here was to allow for 'diff-so-fancy' to be used as a custom pager: https://github.com/jesseduffield/lazygit/issues/190. Another custom pager requested is delta. We've also had a request for side-by-side diffs, which as far as I know can be facilitated by the ydiff pager and not much else. icdiff is a thing but isn't actually a pager, it's a difftool.

I would like the solution to have no knowledge about the actual pagers available. That way if a new pager shows up and gets popular, it will already be supported. I am open to different opinions on this.

Here is the proposed config:
```
git
  paging:
    useConfig: true/false
    pager: string // ignored when useConfig is true
    colorArg: always/never
```
If you want to make use of what's in your git config you can use the following:
```
git
  paging:
    useConfig: true
```
and if your config sets the pager as `diff-so-fancy | less` we'll truncate the `| less` part. If you specify the pager directly  with the `git.paging.pager` key we'll use it as-is. It's up to you to set the colorArg to whatever it needs to be given your pager.

If you want to use `ydiff` for a side-by-side view you'll want to use this:
```
git
  paging:
    pager: ydiff -s --wrap --width={{columnWidth}}
    colorArg: never
```
Inside lazygit we'll resolve that template with the actual column width.

Okay here's all the nuances that have contributed to my proposal
1) For git to make use of the $GIT_PAGER env variable, it needs its output to be a terminal. This requires us to wrap the git diff command in a pty, and the pty package is only available for windows. For this reason, the feature won't be available for windows (windows WSL should be fine)
2) The $GIT_PAGER env var might contain something like `diff-so-fancy | less -SFX` which we actually don't want. We don't want less to run given we're just writing all the output to our panel and have no way of telling less to scroll down or quit.
3) diff-so-fancy needs the color arg to be set to 'always' or it won't format correctly. Delta doesn't care either way. ydiff requires the arg to be set to 'never'. The only way to deal with this discrepancy without making lazygit knowledgeable of the different permutations is to add it to the lazygit config.
4) Unlike diff-so-fancy, ydiff and delta both use less under the hood (by the looks of it) when there's more than one page to show. That basically breaks them, and we end up with a weird delay where upon selecting the next line, the previous line's diff is shown. I could not find a way around this. Maybe it's a matter of putting up PRs on the respective repos to add a flag for '--no-pager'. I've raised an issue for delta here: https://github.com/dandavison/delta/issues/108. Given a user could have one of these set in their config and it's gonna break lazygit, we set `git.paging.useConfig` to false by default.
5) delta uses way more than 256 colours, but gocui only supports 256. That means the the colours don't come through correctly. This PR https://github.com/dandavison/delta/pull/46 is working on it

### CODE REVIEW

**Comment by dandavison** [comment]
@jesseduffield Regarding integrating delta as a diff viewer,

1. Thanks for your PR https://github.com/dandavison/delta/pull/109! So to repeat that PR's conclusion here, with delta built from its master branch, one can pass `--paging=never` to disable all paging of stdout.

2. I've merged a PR https://github.com/dandavison/delta/pull/111 which adds support for 256 color terminal environments. So, on delta master branch you can now pass `--24-bit-color=never`. This will (a) choose good 8-bit color defaults, and (b) convert any 24 bit colors implied by the user's config (e.g. their `~/.gitconfig`, `BAT_THEME` etc)  to the closest 8-bit approximation.

I'm happy to get a delta release out to coordinate with the feature you're working on here. (And of course let me know if either of those recent delta changes don't seem to be working as intended!)

**Comment by jesseduffield** [comment]
Thanks @dandavison for helping out! The result looks pretty good, although it seems like lazygit is failing to reset the background color. I'll need to have a look into how it deals with a color reset ansi sequences.

image

**Comment by jesseduffield** [comment]
@dandavison would you happen to know how the background color is being reset by delta? Perhaps with `\033[0m`? I'm wondering if I don't support the escape sequence being used

**Comment by dandavison** [comment]
@jesseduffield when you get a chance could you try delta's master branch? I'm hoping https://github.com/dandavison/delta/pull/114 will solve the issues you're seeing with colors over-running / not being reset.

**Comment by jesseduffield** [comment]
@dandavison works like a charm, thanks :)

**Comment by jesseduffield** [comment]
Here's how it currently looks:
image

It's a shame that the darkest green in 256 colours is actually not that dark, meaning it can be a little hard to see newly added code. Light mode looks much nicer. But to support 24 bit color I've gotta go two layers deep in our dependencies: gocui doesn't support it and neither does termbox which gocui is built on top of. At any rate I think this is a good outcome :)

**Comment by mattpass** [comment]
@jesseduffield great to see this PR was merged in. Will the new Launchpad release be pushed out soon so I can update and try it out?

**Comment by dawidd6** [comment]
@mattpass done

**Comment by dandavison** [comment]
I've released version 0.0.17 of [delta](https://github.com/dandavison/delta), which has the changes necessary to work as a custom pager for lazygit.

**Comment by jesseduffield** [comment]
Thanks!

**Comment by mattpass** [comment]
Only just getting around to checking this out today but updated and is working great. Many thanks!

**Pull request merged**
