### PR TITLE
Display Nerdfont icons

### PR DESCRIPTION
**Pull request by Ryooooooga**
<table>
<tr>
	<th>files
	<td>file-icons
<tr>
	<th>commits
	<td>commits
<tr>
	<th>branches
	<td>branches
<tr>
	<th>remotes
	<td>remotes
</table>

### CODE REVIEW

**Review by jesseduffield — CHANGES_REQUESTED** [review]
Sorry for the late review @Ryooooooga I've been sick.

Awesome work! Could we add some documentation about how to get a font that will display the icons?

**Comment by Ryooooooga** [comment]
@jesseduffield Bless you. I have added documentation on config.

**Comment by jesseduffield** [comment]
Merged. Great work! I'll be using this myself

**Comment by mark2185** [comment]
Is this expected? I'm having a hard time parsing what exactly am I looking at with these icons.

image

**Comment by jesseduffield** [comment]
@mark2185 you'll need to get a proper nerd font for the icons to render properly

**Comment by mark2185** [comment]
Good guess, but it's actually due to the terminal emulator. Guess I'll have to switch. Sorry for the noise!

**Comment by jesseduffield** [comment]
hmm do you reckon that's something we should be capturing in our docs @mark2185 @Ryooooooga ?

**Comment by mark2185** [comment]
Maybe? Just a "if it doesn't work, try different terminal emulators" will probably suffice.

**Comment by Ryooooooga** [comment]
What environment and fonts are you using?

**Comment by mark2185** [comment]
Archlinux with [terminator](https://github.com/gnome-terminator/terminator) and [Source Code Pro Medium 10](https://fonts.google.com/specimen/Source+Code+Pro). Tried it with [kitty](https://github.com/kovidgoyal/kitty) and it works as expected.

For comparison, terminator:
image

Kitty:
image


The branch glyph in `kitty` looks weird, but at least it's in the right place.

**Pull request merged**
