### PR TITLE
Add "CopyCommitURLToClipboard" option

### LINKED ISSUE #1768: Copy commit to clipboard (instead of open in browser)
**Is your feature request related to a problem? Please describe.**
Most of the times I don't want to open the commit in a browser, I see the commit in lazygit, I just want a link to send it to a colleague.
Or if I'm working in a container, I don't have a browser that can be opened.

**Describe the solution you'd like**
```
o    open commit in browser
O   copy commit URL to clibpoard
```
**Describe alternatives you've considered**
Writing a custom command for it seems too complex since there are several hosting services. 

**Additional context**
I'd like to take a shot at this, I'm just opening an issue lest I forget.

I see that `handleOpenCommitInBrowser` uses `hostingServiceMgr.GetCommitURL(commit.Sha)` and there exists `os.CopyToClipboard` so I'm guessing it's not too hard to connect the wires.

### PR DESCRIPTION
**Pull request by mark2185**
I'll take all the pointers I can get, please.

This closes #1768 .

### CODE REVIEW

**Comment by mark2185** [comment]
Oh and yeah, this closes #1768 .

**Comment by jesseduffield** [comment]
Code looks good, my only hesitation is around keybinding realestate: there's quite a few things you might want to copy from a commit:
* SHA
* message
* url
* timestamp (contrived I know)

I wonder if we should be putting these copy-to-clipboard options behind a menu, rather than finding a new keybinding for each new use case. What do you think?

**Comment by mark2185** [comment]
_I concur._

I'd only pitch in `commit diff` into that pool, so I can "export" it as a patch.

**Comment by jesseduffield** [comment]
@mark2185 that's a good idea, I hadn't thought of that

**Comment by mark2185** [comment]
@jesseduffield except that the `diff` isn't parsed from the `git log`. If I'm looking in [the right place](https://github.com/jesseduffield/lazygit/blob/5ded030a884b6358da34ddd5b855e0f2cb005d24/pkg/commands/loaders/commits.go#L158-L159).

**Pull request closed without merging**
