### PR TITLE
Handle files with spaces in git diff

### PR DESCRIPTION
**Pull request by dawidd6**
Fixes: #100

### CODE REVIEW

**Comment by fiendish** [comment]
maybe if it doesn't work on windows someone who uses windows will file a bug report?

**Comment by jesseduffield** [comment]
@fiendish yeah I'm happy to go down that path. It would be good to add some ability for users to agree to sending report data so that we can work out what the platform distribution of our audience is, because for all I know there aren't many windows users.

@dawidd6 I branched off this to add support for filenames without spaces. Would you be able to merge that into your branch and then add support for staging/unstaging filenames with spaces? Otherwise there's not much use in the diff feature. (Also I have no idea if it makes sense for me to make a new PR if I want to add things to a PR off a forked repo, am I doing it right haha?)

**Comment by dawidd6** [comment]
@jesseduffield hmm, apparently you as an owner can push commits to this pull request directly, see:
https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by jesseduffield** [comment]
@dawidd6 cool stuff I just followed those steps and pushed my changes to this PR

**Comment by andreimc** [comment]
@jesseduffield we need to port some of this pull requests into the new structure

**Comment by jesseduffield** [comment]
Closing, as I've ported this to the new structure :)

**Pull request closed without merging**
