### PR TITLE
Add codespell support (config, workflow to detect/not fix) and make it fix few typos

### PR DESCRIPTION
**Pull request by yarikoptic**
More about codespell: https://github.com/codespell-project/codespell .

I personally introduced it to dozens if not hundreds of projects already and so far only positive feedback.

CI workflow has 'permissions' set only to 'read' so also should be safe.

### CODE REVIEW

**Comment by jesseduffield** [comment]
Thanks for raising this. 

I was pretty skeptical at first because I've had random tooling added in PRs before which ended up just being extra work to maintain, but this seems to genuinely do a good job of finding spelling mistakes with very few false positives, so I'm happy to include this, with the caveat that if it becomes annoying I have no compunctions about removing it.

**Review by jesseduffield — APPROVED** [review]

**Comment by jesseduffield** [comment]
Looks like it's caught some more issues after rebasing @yarikoptic . Could you fix those up?

**Comment by yarikoptic** [comment]
> with the caveat that if it becomes annoying I have no compunctions about removing it.

My *compunction* of not knowing what *compunction* is ;)  now I do (kinda)

> Looks like it's caught some more issues after rebasing @yarikoptic . Could you fix those up?

yeah, caught more with some freshier codespell, so I rebased (again as you did, to ensure master has nothing new) with sign off and redone overall fixing and some interactive one for those new ones.

**Comment by yarikoptic** [comment]
CI got stuck? could be restarted?

**Comment by stefanhaller** [comment]
I took the liberty of rebasing on master again, it was already behind again. No new failures this time, so I'm gonna merge as soon as CI is done.

Thanks!

**Pull request merged**
