### PR TITLE
Switch from CircleCI to Github Actions

### PR DESCRIPTION
**Pull request by dawidd6**

### CODE REVIEW

**Comment by jesseduffield** [comment]
Is this a response to https://github.com/jesseduffield/lazygit/issues/708? I thought it was only golangci that was shutting down, not circleCI. At any rate I'm happy to make the change :) Is there anything I need to do to remove the calls to circleCI?

**Comment by dawidd6** [comment]
It's more likely a response to the fact that latest releases recently lack built binaries and changelogs (I suppose you just did `git tag` instead of pushing release button on Github?).

As of golangci, I don't know yet, there are Actions for that but they need GITHUB_TOKEN secret to be able to post annotations on PR changes and secrets are not available for PRs created from forked repos.

**Comment by jesseduffield** [comment]
interesting, I've always just made a tag and pushed it. Wonder what's changed. At any rate I'm happy to go ahead with this. Are you happy for this to be merged?

**Comment by dawidd6** [comment]
Let's wait a bit with that yet.

**Comment by dawidd6** [comment]
Now it's ready to be merged, but without codecov and linter, it would need to be handled by Codacy or CodeClimate as stated here: https://github.com/jesseduffield/lazygit/issues/708#issuecomment-601448727

**Comment by jesseduffield** [comment]
I'm sick of codecov anyway haha. Mergin

**Pull request merged**
